spring:
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/ifmix_core}
      auto-index-creation: true
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

server:
  port: ${PORT:3001}

springdoc:
  swagger-ui:
    persist-authorization: true

app:
  expose-errors: ${APP_EXPOSE_ERRORS:true}
  storage:
    type: ${STORAGE_TYPE:none}
    region: ${STORAGE_REGION:us-east-1}
    endpoint: ${STORAGE_ENDPOINT:http://localhost:9000}
    bucket: ${STORAGE_BUCKET:ifmix}
    access-key: ${STORAGE_ACCESS_KEY:minioadmin}
    secret-key: ${STORAGE_SECRET_KEY:minioadmin}
