input PresignUploadInput {
    "上传分类。100=ANTIQUE_SCAN"
    category: Int!
    "内容类型。100=IMAGE_JPEG, 200=IMAGE_PNG, 300=IMAGE_WEBP"
    contentType: Int!
}

type PresignUploadPayload {
    mediaId: UUID!
    uploadUrl: String!
    imageKey: String!
    downloadUrl: String!
}

input PresignDownloadInput {
    imageKey: String!
    durationSeconds: Int
}

type PresignDownloadPayload {
    url: String!
}

extend type Mutation {
    mutation_storage_presignUpload(input: PresignUploadInput!): PresignUploadPayload!
    mutation_storage_presignDownload(input: PresignDownloadInput!): PresignDownloadPayload!
}
