/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.pojos


import java.io.Serializable
import java.time.Instant
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class CoreTodo(
    var id: UUID,
    var title: String,
    var done: Boolean? = null,
    var appId: UUID,
    var createdAt: Instant,
    var updatedAt: Instant,
    var deletedAt: Instant? = null,
    var installId: UUID? = null,
    var userId: UUID? = null,
    var meta: JSONB? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: CoreTodo = other as CoreTodo
        if (this.id != o.id)
            return false
        if (this.title != o.title)
            return false
        if (this.done == null) {
            if (o.done != null)
                return false
        }
        else if (this.done != o.done)
            return false
        if (this.appId != o.appId)
            return false
        if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt != o.updatedAt)
            return false
        if (this.deletedAt == null) {
            if (o.deletedAt != null)
                return false
        }
        else if (this.deletedAt != o.deletedAt)
            return false
        if (this.installId == null) {
            if (o.installId != null)
                return false
        }
        else if (this.installId != o.installId)
            return false
        if (this.userId == null) {
            if (o.userId != null)
                return false
        }
        else if (this.userId != o.userId)
            return false
        if (this.meta == null) {
            if (o.meta != null)
                return false
        }
        else if (this.meta != o.meta)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.title.hashCode()
        result = prime * result + (if (this.done == null) 0 else this.done.hashCode())
        result = prime * result + this.appId.hashCode()
        result = prime * result + this.createdAt.hashCode()
        result = prime * result + this.updatedAt.hashCode()
        result = prime * result + (if (this.deletedAt == null) 0 else this.deletedAt.hashCode())
        result = prime * result + (if (this.installId == null) 0 else this.installId.hashCode())
        result = prime * result + (if (this.userId == null) 0 else this.userId.hashCode())
        result = prime * result + (if (this.meta == null) 0 else this.meta.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("CoreTodo (")

        sb.append(id)
        sb.append(", ").append(title)
        sb.append(", ").append(done)
        sb.append(", ").append(appId)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(deletedAt)
        sb.append(", ").append(installId)
        sb.append(", ").append(userId)
        sb.append(", ").append(meta)

        sb.append(")")
        return sb.toString()
    }
}
