/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.pojos


import java.io.Serializable
import java.time.Instant
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class CoreSubscription(
    var id: UUID,
    var appId: UUID,
    var subscriptionPxid: String? = null,
    var originalTransactionId: String? = null,
    var productId: String? = null,
    var platform: Short? = null,
    var active: Boolean? = null,
    var subStatus: String? = null,
    var expiryDate: Instant? = null,
    var purchaseToken: String? = null,
    var rawResponse: JSONB? = null,
    var createdAt: Instant? = null,
    var updatedAt: Instant? = null,
    var deletedAt: Instant? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: CoreSubscription = other as CoreSubscription
        if (this.id != o.id)
            return false
        if (this.appId != o.appId)
            return false
        if (this.subscriptionPxid == null) {
            if (o.subscriptionPxid != null)
                return false
        }
        else if (this.subscriptionPxid != o.subscriptionPxid)
            return false
        if (this.originalTransactionId == null) {
            if (o.originalTransactionId != null)
                return false
        }
        else if (this.originalTransactionId != o.originalTransactionId)
            return false
        if (this.productId == null) {
            if (o.productId != null)
                return false
        }
        else if (this.productId != o.productId)
            return false
        if (this.platform == null) {
            if (o.platform != null)
                return false
        }
        else if (this.platform != o.platform)
            return false
        if (this.active == null) {
            if (o.active != null)
                return false
        }
        else if (this.active != o.active)
            return false
        if (this.subStatus == null) {
            if (o.subStatus != null)
                return false
        }
        else if (this.subStatus != o.subStatus)
            return false
        if (this.expiryDate == null) {
            if (o.expiryDate != null)
                return false
        }
        else if (this.expiryDate != o.expiryDate)
            return false
        if (this.purchaseToken == null) {
            if (o.purchaseToken != null)
                return false
        }
        else if (this.purchaseToken != o.purchaseToken)
            return false
        if (this.rawResponse == null) {
            if (o.rawResponse != null)
                return false
        }
        else if (this.rawResponse != o.rawResponse)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt == null) {
            if (o.updatedAt != null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        if (this.deletedAt == null) {
            if (o.deletedAt != null)
                return false
        }
        else if (this.deletedAt != o.deletedAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.appId.hashCode()
        result = prime * result + (if (this.subscriptionPxid == null) 0 else this.subscriptionPxid.hashCode())
        result = prime * result + (if (this.originalTransactionId == null) 0 else this.originalTransactionId.hashCode())
        result = prime * result + (if (this.productId == null) 0 else this.productId.hashCode())
        result = prime * result + (if (this.platform == null) 0 else this.platform.hashCode())
        result = prime * result + (if (this.active == null) 0 else this.active.hashCode())
        result = prime * result + (if (this.subStatus == null) 0 else this.subStatus.hashCode())
        result = prime * result + (if (this.expiryDate == null) 0 else this.expiryDate.hashCode())
        result = prime * result + (if (this.purchaseToken == null) 0 else this.purchaseToken.hashCode())
        result = prime * result + (if (this.rawResponse == null) 0 else this.rawResponse.hashCode())
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt == null) 0 else this.updatedAt.hashCode())
        result = prime * result + (if (this.deletedAt == null) 0 else this.deletedAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("CoreSubscription (")

        sb.append(id)
        sb.append(", ").append(appId)
        sb.append(", ").append(subscriptionPxid)
        sb.append(", ").append(originalTransactionId)
        sb.append(", ").append(productId)
        sb.append(", ").append(platform)
        sb.append(", ").append(active)
        sb.append(", ").append(subStatus)
        sb.append(", ").append(expiryDate)
        sb.append(", ").append(purchaseToken)
        sb.append(", ").append(rawResponse)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(deletedAt)

        sb.append(")")
        return sb.toString()
    }
}
