/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.pojos


import java.io.Serializable
import java.time.Instant
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class CoreAgnesKey(
    var id: UUID,
    var appId: UUID,
    var key: String,
    var email: String? = null,
    var rateLimit: Long? = null,
    var windowSec: Long? = null,
    var models: String? = null,
    var unavailableUntil: Instant? = null,
    var createdAt: Instant? = null,
    var updatedAt: Instant? = null,
    var deletedAt: Instant? = null,
    var type: Int? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: CoreAgnesKey = other as CoreAgnesKey
        if (this.id != o.id)
            return false
        if (this.appId != o.appId)
            return false
        if (this.key != o.key)
            return false
        if (this.email == null) {
            if (o.email != null)
                return false
        }
        else if (this.email != o.email)
            return false
        if (this.rateLimit == null) {
            if (o.rateLimit != null)
                return false
        }
        else if (this.rateLimit != o.rateLimit)
            return false
        if (this.windowSec == null) {
            if (o.windowSec != null)
                return false
        }
        else if (this.windowSec != o.windowSec)
            return false
        if (this.models == null) {
            if (o.models != null)
                return false
        }
        else if (this.models != o.models)
            return false
        if (this.unavailableUntil == null) {
            if (o.unavailableUntil != null)
                return false
        }
        else if (this.unavailableUntil != o.unavailableUntil)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt == null) {
            if (o.updatedAt != null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        if (this.deletedAt == null) {
            if (o.deletedAt != null)
                return false
        }
        else if (this.deletedAt != o.deletedAt)
            return false
        if (this.type == null) {
            if (o.type != null)
                return false
        }
        else if (this.type != o.type)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.appId.hashCode()
        result = prime * result + this.key.hashCode()
        result = prime * result + (if (this.email == null) 0 else this.email.hashCode())
        result = prime * result + (if (this.rateLimit == null) 0 else this.rateLimit.hashCode())
        result = prime * result + (if (this.windowSec == null) 0 else this.windowSec.hashCode())
        result = prime * result + (if (this.models == null) 0 else this.models.hashCode())
        result = prime * result + (if (this.unavailableUntil == null) 0 else this.unavailableUntil.hashCode())
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt == null) 0 else this.updatedAt.hashCode())
        result = prime * result + (if (this.deletedAt == null) 0 else this.deletedAt.hashCode())
        result = prime * result + (if (this.type == null) 0 else this.type.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("CoreAgnesKey (")

        sb.append(id)
        sb.append(", ").append(appId)
        sb.append(", ").append(key)
        sb.append(", ").append(email)
        sb.append(", ").append(rateLimit)
        sb.append(", ").append(windowSec)
        sb.append(", ").append(models)
        sb.append(", ").append(unavailableUntil)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(deletedAt)
        sb.append(", ").append(type)

        sb.append(")")
        return sb.toString()
    }
}
