/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.pojos


import java.io.Serializable
import java.time.Instant
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class CoreScanCollection(
    var id: UUID,
    var appId: UUID,
    var installId: UUID? = null,
    var userId: String? = null,
    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDefault")
    var isDefault: Boolean? = null,
    var createdAt: Instant? = null,
    var updatedAt: Instant? = null,
    var deletedAt: Instant? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: CoreScanCollection = other as CoreScanCollection
        if (this.id != o.id)
            return false
        if (this.appId != o.appId)
            return false
        if (this.installId == null) {
            if (o.installId != null)
                return false
        }
        else if (this.installId != o.installId)
            return false
        if (this.userId == null) {
            if (o.userId != null)
                return false
        }
        else if (this.userId != o.userId)
            return false
        if (this.isDefault == null) {
            if (o.isDefault != null)
                return false
        }
        else if (this.isDefault != o.isDefault)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt == null) {
            if (o.updatedAt != null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        if (this.deletedAt == null) {
            if (o.deletedAt != null)
                return false
        }
        else if (this.deletedAt != o.deletedAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.appId.hashCode()
        result = prime * result + (if (this.installId == null) 0 else this.installId.hashCode())
        result = prime * result + (if (this.userId == null) 0 else this.userId.hashCode())
        result = prime * result + (if (this.isDefault == null) 0 else this.isDefault.hashCode())
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt == null) 0 else this.updatedAt.hashCode())
        result = prime * result + (if (this.deletedAt == null) 0 else this.deletedAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("CoreScanCollection (")

        sb.append(id)
        sb.append(", ").append(appId)
        sb.append(", ").append(installId)
        sb.append(", ").append(userId)
        sb.append(", ").append(isDefault)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(deletedAt)

        sb.append(")")
        return sb.toString()
    }
}
