/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.pojos


import java.io.Serializable
import java.time.Instant
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class CoreTodoItem(
    var id: UUID,
    var todoId: UUID,
    var appId: UUID,
    var content: String,
    var done: Boolean? = null,
    var createdAt: Instant,
    var updatedAt: Instant,
    var deletedAt: Instant? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: CoreTodoItem = other as CoreTodoItem
        if (this.id != o.id)
            return false
        if (this.todoId != o.todoId)
            return false
        if (this.appId != o.appId)
            return false
        if (this.content != o.content)
            return false
        if (this.done == null) {
            if (o.done != null)
                return false
        }
        else if (this.done != o.done)
            return false
        if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt != o.updatedAt)
            return false
        if (this.deletedAt == null) {
            if (o.deletedAt != null)
                return false
        }
        else if (this.deletedAt != o.deletedAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.todoId.hashCode()
        result = prime * result + this.appId.hashCode()
        result = prime * result + this.content.hashCode()
        result = prime * result + (if (this.done == null) 0 else this.done.hashCode())
        result = prime * result + this.createdAt.hashCode()
        result = prime * result + this.updatedAt.hashCode()
        result = prime * result + (if (this.deletedAt == null) 0 else this.deletedAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("CoreTodoItem (")

        sb.append(id)
        sb.append(", ").append(todoId)
        sb.append(", ").append(appId)
        sb.append(", ").append(content)
        sb.append(", ").append(done)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(deletedAt)

        sb.append(")")
        return sb.toString()
    }
}
