/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.pojos


import java.io.Serializable
import java.time.Instant
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class CoreAppRefreshToken(
    var id: UUID,
    var appId: UUID,
    var appUserId: UUID,
    var deviceSecretId: UUID? = null,
    var tokenHash: String,
    var loginInstallId: UUID? = null,
    var expiresAt: Instant? = null,
    var revokedAt: Instant? = null,
    var replacedBy: UUID? = null,
    var createdAt: Instant? = null,
    var updatedAt: Instant? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: CoreAppRefreshToken = other as CoreAppRefreshToken
        if (this.id != o.id)
            return false
        if (this.appId != o.appId)
            return false
        if (this.appUserId != o.appUserId)
            return false
        if (this.deviceSecretId == null) {
            if (o.deviceSecretId != null)
                return false
        }
        else if (this.deviceSecretId != o.deviceSecretId)
            return false
        if (this.tokenHash != o.tokenHash)
            return false
        if (this.loginInstallId == null) {
            if (o.loginInstallId != null)
                return false
        }
        else if (this.loginInstallId != o.loginInstallId)
            return false
        if (this.expiresAt == null) {
            if (o.expiresAt != null)
                return false
        }
        else if (this.expiresAt != o.expiresAt)
            return false
        if (this.revokedAt == null) {
            if (o.revokedAt != null)
                return false
        }
        else if (this.revokedAt != o.revokedAt)
            return false
        if (this.replacedBy == null) {
            if (o.replacedBy != null)
                return false
        }
        else if (this.replacedBy != o.replacedBy)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt == null) {
            if (o.updatedAt != null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.appId.hashCode()
        result = prime * result + this.appUserId.hashCode()
        result = prime * result + (if (this.deviceSecretId == null) 0 else this.deviceSecretId.hashCode())
        result = prime * result + this.tokenHash.hashCode()
        result = prime * result + (if (this.loginInstallId == null) 0 else this.loginInstallId.hashCode())
        result = prime * result + (if (this.expiresAt == null) 0 else this.expiresAt.hashCode())
        result = prime * result + (if (this.revokedAt == null) 0 else this.revokedAt.hashCode())
        result = prime * result + (if (this.replacedBy == null) 0 else this.replacedBy.hashCode())
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt == null) 0 else this.updatedAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("CoreAppRefreshToken (")

        sb.append(id)
        sb.append(", ").append(appId)
        sb.append(", ").append(appUserId)
        sb.append(", ").append(deviceSecretId)
        sb.append(", ").append(tokenHash)
        sb.append(", ").append(loginInstallId)
        sb.append(", ").append(expiresAt)
        sb.append(", ").append(revokedAt)
        sb.append(", ").append(replacedBy)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)

        sb.append(")")
        return sb.toString()
    }
}
