/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.pojos


import java.io.Serializable
import java.time.Instant
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class CoreFeedback(
    var id: UUID,
    var appId: UUID,
    var installId: UUID,
    var userId: UUID? = null,
    var scanRecordId: UUID? = null,
    var category: Short? = null,
    var comment: String? = null,
    var createdAt: Instant
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: CoreFeedback = other as CoreFeedback
        if (this.id != o.id)
            return false
        if (this.appId != o.appId)
            return false
        if (this.installId != o.installId)
            return false
        if (this.userId == null) {
            if (o.userId != null)
                return false
        }
        else if (this.userId != o.userId)
            return false
        if (this.scanRecordId == null) {
            if (o.scanRecordId != null)
                return false
        }
        else if (this.scanRecordId != o.scanRecordId)
            return false
        if (this.category == null) {
            if (o.category != null)
                return false
        }
        else if (this.category != o.category)
            return false
        if (this.comment == null) {
            if (o.comment != null)
                return false
        }
        else if (this.comment != o.comment)
            return false
        if (this.createdAt != o.createdAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.appId.hashCode()
        result = prime * result + this.installId.hashCode()
        result = prime * result + (if (this.userId == null) 0 else this.userId.hashCode())
        result = prime * result + (if (this.scanRecordId == null) 0 else this.scanRecordId.hashCode())
        result = prime * result + (if (this.category == null) 0 else this.category.hashCode())
        result = prime * result + (if (this.comment == null) 0 else this.comment.hashCode())
        result = prime * result + this.createdAt.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("CoreFeedback (")

        sb.append(id)
        sb.append(", ").append(appId)
        sb.append(", ").append(installId)
        sb.append(", ").append(userId)
        sb.append(", ").append(scanRecordId)
        sb.append(", ").append(category)
        sb.append(", ").append(comment)
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }
}
