/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreAuthIdentity

import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAuthIdentityRecord private constructor() : UpdatableRecordImpl<CoreAuthIdentityRecord>(CoreAuthIdentity.CORE_AUTH_IDENTITY) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var authTenantId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var rawEmail: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var email: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var rawPhone: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var phone: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var contactEmail: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var displayName: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var passwordHash: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var profile: JSONB?
        set(value): Unit = set(9, value)
        get(): JSONB? = get(9) as JSONB?

    open var metadata: JSONB?
        set(value): Unit = set(10, value)
        get(): JSONB? = get(10) as JSONB?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(11, value)
        get(): OffsetDateTime? = get(11) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(12, value)
        get(): OffsetDateTime? = get(12) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreAuthIdentityRecord
     */
    constructor(id: UUID, authTenantId: UUID, rawEmail: String? = null, email: String? = null, rawPhone: String? = null, phone: String? = null, contactEmail: String? = null, displayName: String? = null, passwordHash: String? = null, profile: JSONB? = null, metadata: JSONB? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.authTenantId = authTenantId
        this.rawEmail = rawEmail
        this.email = email
        this.rawPhone = rawPhone
        this.phone = phone
        this.contactEmail = contactEmail
        this.displayName = displayName
        this.passwordHash = passwordHash
        this.profile = profile
        this.metadata = metadata
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
