/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreAgnesKey

import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAgnesKeyRecord private constructor() : UpdatableRecordImpl<CoreAgnesKeyRecord>(CoreAgnesKey.CORE_AGNES_KEY) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var appId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var key: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var email: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var rateLimit: Long?
        set(value): Unit = set(4, value)
        get(): Long? = get(4) as Long?

    open var windowSec: Long?
        set(value): Unit = set(5, value)
        get(): Long? = get(5) as Long?

    open var models: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var unavailableUntil: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(8, value)
        get(): OffsetDateTime? = get(8) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(9, value)
        get(): OffsetDateTime? = get(9) as OffsetDateTime?

    open var deletedAt: OffsetDateTime?
        set(value): Unit = set(10, value)
        get(): OffsetDateTime? = get(10) as OffsetDateTime?

    open var type: Short?
        set(value): Unit = set(11, value)
        get(): Short? = get(11) as Short?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreAgnesKeyRecord
     */
    constructor(id: UUID, appId: UUID, key: String, email: String? = null, rateLimit: Long? = null, windowSec: Long? = null, models: String? = null, unavailableUntil: OffsetDateTime? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null, deletedAt: OffsetDateTime? = null, type: Short? = null): this() {
        this.id = id
        this.appId = appId
        this.key = key
        this.email = email
        this.rateLimit = rateLimit
        this.windowSec = windowSec
        this.models = models
        this.unavailableUntil = unavailableUntil
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.deletedAt = deletedAt
        this.type = type
        resetTouchedOnNotNull()
    }
}
