/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreAuthTenant

import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAuthTenantRecord private constructor() : UpdatableRecordImpl<CoreAuthTenantRecord>(CoreAuthTenant.CORE_AUTH_TENANT) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var jwtPrivateKeyPem: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var jwtIssuer: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreAuthTenantRecord
     */
    constructor(id: UUID, jwtPrivateKeyPem: String? = null, jwtIssuer: String? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.jwtPrivateKeyPem = jwtPrivateKeyPem
        this.jwtIssuer = jwtIssuer
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
