/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreScanRecord

import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreScanRecordRecord private constructor() : UpdatableRecordImpl<CoreScanRecordRecord>(CoreScanRecord.CORE_SCAN_RECORD) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var appId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var resultJson: JSONB?
        set(value): Unit = set(2, value)
        get(): JSONB? = get(2) as JSONB?

    open var status: Short?
        set(value): Unit = set(3, value)
        get(): Short? = get(3) as Short?

    open var clientIp: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var deletedAt: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    open var imageKeys: JSONB?
        set(value): Unit = set(8, value)
        get(): JSONB? = get(8) as JSONB?

    open var userDisplayName: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var userNotes: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var collected: Boolean?
        set(value): Unit = set(11, value)
        get(): Boolean? = get(11) as Boolean?

    open var lang: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var country: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    open var currency: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreScanRecordRecord
     */
    constructor(id: UUID, appId: UUID, resultJson: JSONB? = null, status: Short? = null, clientIp: String? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null, deletedAt: OffsetDateTime? = null, imageKeys: JSONB? = null, userDisplayName: String? = null, userNotes: String? = null, collected: Boolean? = null, lang: String? = null, country: String? = null, currency: String? = null): this() {
        this.id = id
        this.appId = appId
        this.resultJson = resultJson
        this.status = status
        this.clientIp = clientIp
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.deletedAt = deletedAt
        this.imageKeys = imageKeys
        this.userDisplayName = userDisplayName
        this.userNotes = userNotes
        this.collected = collected
        this.lang = lang
        this.country = country
        this.currency = currency
        resetTouchedOnNotNull()
    }
}
