/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreAuthDeviceSecret

import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAuthDeviceSecretRecord private constructor() : UpdatableRecordImpl<CoreAuthDeviceSecretRecord>(CoreAuthDeviceSecret.CORE_AUTH_DEVICE_SECRET) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var authTenantId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var authIdentityId: UUID
        set(value): Unit = set(2, value)
        get(): UUID = get(2) as UUID

    open var secretHash: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var loginInstallId: UUID?
        set(value): Unit = set(4, value)
        get(): UUID? = get(4) as UUID?

    open var expiresAt: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open var revokedAt: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var lastUsedAt: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(8, value)
        get(): OffsetDateTime? = get(8) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(9, value)
        get(): OffsetDateTime? = get(9) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreAuthDeviceSecretRecord
     */
    constructor(id: UUID, authTenantId: UUID, authIdentityId: UUID, secretHash: String, loginInstallId: UUID? = null, expiresAt: OffsetDateTime? = null, revokedAt: OffsetDateTime? = null, lastUsedAt: OffsetDateTime? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.authTenantId = authTenantId
        this.authIdentityId = authIdentityId
        this.secretHash = secretHash
        this.loginInstallId = loginInstallId
        this.expiresAt = expiresAt
        this.revokedAt = revokedAt
        this.lastUsedAt = lastUsedAt
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
