/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreAppUser

import java.time.Instant
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAppUserRecord private constructor() : UpdatableRecordImpl<CoreAppUserRecord>(CoreAppUser.CORE_APP_USER) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var appId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var authIdentityId: UUID
        set(value): Unit = set(2, value)
        get(): UUID = get(2) as UUID

    open var metadata: JSONB?
        set(value): Unit = set(3, value)
        get(): JSONB? = get(3) as JSONB?

    open var createdAt: Instant?
        set(value): Unit = set(4, value)
        get(): Instant? = get(4) as Instant?

    open var updatedAt: Instant?
        set(value): Unit = set(5, value)
        get(): Instant? = get(5) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreAppUserRecord
     */
    constructor(id: UUID, appId: UUID, authIdentityId: UUID, metadata: JSONB? = null, createdAt: Instant? = null, updatedAt: Instant? = null): this() {
        this.id = id
        this.appId = appId
        this.authIdentityId = authIdentityId
        this.metadata = metadata
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised CoreAppUserRecord
     */
    constructor(value: com.ifmix.api.core.jooq.tables.pojos.CoreAppUser?): this() {
        if (value != null) {
            this.id = value.id
            this.appId = value.appId
            this.authIdentityId = value.authIdentityId
            this.metadata = value.metadata
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            resetTouchedOnNotNull()
        }
    }
}
