/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreStoreNotification

import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreStoreNotificationRecord private constructor() : UpdatableRecordImpl<CoreStoreNotificationRecord>(CoreStoreNotification.CORE_STORE_NOTIFICATION) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var appId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var platform: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var subscriptionPxid: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var purchaseToken: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var notificationType: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var rawPayload: JSONB?
        set(value): Unit = set(6, value)
        get(): JSONB? = get(6) as JSONB?

    open var processed: Boolean?
        set(value): Unit = set(7, value)
        get(): Boolean? = get(7) as Boolean?

    open var processedAt: OffsetDateTime?
        set(value): Unit = set(8, value)
        get(): OffsetDateTime? = get(8) as OffsetDateTime?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(9, value)
        get(): OffsetDateTime? = get(9) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(10, value)
        get(): OffsetDateTime? = get(10) as OffsetDateTime?

    open var deletedAt: OffsetDateTime?
        set(value): Unit = set(11, value)
        get(): OffsetDateTime? = get(11) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreStoreNotificationRecord
     */
    constructor(id: UUID, appId: UUID, platform: String? = null, subscriptionPxid: String? = null, purchaseToken: String? = null, notificationType: String? = null, rawPayload: JSONB? = null, processed: Boolean? = null, processedAt: OffsetDateTime? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null, deletedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.appId = appId
        this.platform = platform
        this.subscriptionPxid = subscriptionPxid
        this.purchaseToken = purchaseToken
        this.notificationType = notificationType
        this.rawPayload = rawPayload
        this.processed = processed
        this.processedAt = processedAt
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.deletedAt = deletedAt
        resetTouchedOnNotNull()
    }
}
