/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreAgnesKey

import java.time.Instant
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAgnesKeyRecord private constructor() : UpdatableRecordImpl<CoreAgnesKeyRecord>(CoreAgnesKey.CORE_AGNES_KEY) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var appId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var key: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var email: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var rateLimit: Long?
        set(value): Unit = set(4, value)
        get(): Long? = get(4) as Long?

    open var windowSec: Long?
        set(value): Unit = set(5, value)
        get(): Long? = get(5) as Long?

    open var models: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var unavailableUntil: Instant?
        set(value): Unit = set(7, value)
        get(): Instant? = get(7) as Instant?

    open var createdAt: Instant?
        set(value): Unit = set(8, value)
        get(): Instant? = get(8) as Instant?

    open var updatedAt: Instant?
        set(value): Unit = set(9, value)
        get(): Instant? = get(9) as Instant?

    open var deletedAt: Instant?
        set(value): Unit = set(10, value)
        get(): Instant? = get(10) as Instant?

    open var type: Int?
        set(value): Unit = set(11, value)
        get(): Int? = get(11) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreAgnesKeyRecord
     */
    constructor(id: UUID, appId: UUID, key: String, email: String? = null, rateLimit: Long? = null, windowSec: Long? = null, models: String? = null, unavailableUntil: Instant? = null, createdAt: Instant? = null, updatedAt: Instant? = null, deletedAt: Instant? = null, type: Int? = null): this() {
        this.id = id
        this.appId = appId
        this.key = key
        this.email = email
        this.rateLimit = rateLimit
        this.windowSec = windowSec
        this.models = models
        this.unavailableUntil = unavailableUntil
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.deletedAt = deletedAt
        this.type = type
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised CoreAgnesKeyRecord
     */
    constructor(value: com.ifmix.api.core.jooq.tables.pojos.CoreAgnesKey?): this() {
        if (value != null) {
            this.id = value.id
            this.appId = value.appId
            this.key = value.key
            this.email = value.email
            this.rateLimit = value.rateLimit
            this.windowSec = value.windowSec
            this.models = value.models
            this.unavailableUntil = value.unavailableUntil
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.deletedAt = value.deletedAt
            this.type = value.type
            resetTouchedOnNotNull()
        }
    }
}
