/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreTodo

import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreTodoRecord private constructor() : UpdatableRecordImpl<CoreTodoRecord>(CoreTodo.CORE_TODO) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var title: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var done: Boolean?
        set(value): Unit = set(2, value)
        get(): Boolean? = get(2) as Boolean?

    open var appId: UUID
        set(value): Unit = set(3, value)
        get(): UUID = get(3) as UUID

    open var createdAt: OffsetDateTime
        set(value): Unit = set(4, value)
        get(): OffsetDateTime = get(4) as OffsetDateTime

    open var updatedAt: OffsetDateTime
        set(value): Unit = set(5, value)
        get(): OffsetDateTime = get(5) as OffsetDateTime

    open var deletedAt: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var installId: UUID?
        set(value): Unit = set(7, value)
        get(): UUID? = get(7) as UUID?

    open var userId: UUID?
        set(value): Unit = set(8, value)
        get(): UUID? = get(8) as UUID?

    open var meta: JSONB?
        set(value): Unit = set(9, value)
        get(): JSONB? = get(9) as JSONB?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreTodoRecord
     */
    constructor(id: UUID, title: String, done: Boolean? = null, appId: UUID, createdAt: OffsetDateTime, updatedAt: OffsetDateTime, deletedAt: OffsetDateTime? = null, installId: UUID? = null, userId: UUID? = null, meta: JSONB? = null): this() {
        this.id = id
        this.title = title
        this.done = done
        this.appId = appId
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.deletedAt = deletedAt
        this.installId = installId
        this.userId = userId
        this.meta = meta
        resetTouchedOnNotNull()
    }
}
