/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreAppConfigRevision

import java.time.Instant
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAppConfigRevisionRecord private constructor() : UpdatableRecordImpl<CoreAppConfigRevisionRecord>(CoreAppConfigRevision.CORE_APP_CONFIG_REVISION) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var appId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var authTenantId: UUID?
        set(value): Unit = set(2, value)
        get(): UUID? = get(2) as UUID?

    open var appleBundleId: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var androidPackageName: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var revisionNumber: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var createdAt: Instant?
        set(value): Unit = set(6, value)
        get(): Instant? = get(6) as Instant?

    open var enabled: Boolean?
        set(value): Unit = set(7, value)
        get(): Boolean? = get(7) as Boolean?

    open var slug: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var content: JSONB?
        set(value): Unit = set(9, value)
        get(): JSONB? = get(9) as JSONB?

    open var note: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreAppConfigRevisionRecord
     */
    constructor(id: UUID, appId: UUID, authTenantId: UUID? = null, appleBundleId: String? = null, androidPackageName: String? = null, revisionNumber: Int? = null, createdAt: Instant? = null, enabled: Boolean? = null, slug: String? = null, content: JSONB? = null, note: String? = null): this() {
        this.id = id
        this.appId = appId
        this.authTenantId = authTenantId
        this.appleBundleId = appleBundleId
        this.androidPackageName = androidPackageName
        this.revisionNumber = revisionNumber
        this.createdAt = createdAt
        this.enabled = enabled
        this.slug = slug
        this.content = content
        this.note = note
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised CoreAppConfigRevisionRecord
     */
    constructor(value: com.ifmix.api.core.jooq.tables.pojos.CoreAppConfigRevision?): this() {
        if (value != null) {
            this.id = value.id
            this.appId = value.appId
            this.authTenantId = value.authTenantId
            this.appleBundleId = value.appleBundleId
            this.androidPackageName = value.androidPackageName
            this.revisionNumber = value.revisionNumber
            this.createdAt = value.createdAt
            this.enabled = value.enabled
            this.slug = value.slug
            this.content = value.content
            this.note = value.note
            resetTouchedOnNotNull()
        }
    }
}
