/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreScanCollectionItem

import java.time.Instant
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreScanCollectionItemRecord private constructor() : UpdatableRecordImpl<CoreScanCollectionItemRecord>(CoreScanCollectionItem.CORE_SCAN_COLLECTION_ITEM) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var appId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var collectionId: UUID
        set(value): Unit = set(2, value)
        get(): UUID = get(2) as UUID

    open var scanRecordId: UUID
        set(value): Unit = set(3, value)
        get(): UUID = get(3) as UUID

    open var createdAt: Instant?
        set(value): Unit = set(4, value)
        get(): Instant? = get(4) as Instant?

    open var updatedAt: Instant?
        set(value): Unit = set(5, value)
        get(): Instant? = get(5) as Instant?

    open var deletedAt: Instant?
        set(value): Unit = set(6, value)
        get(): Instant? = get(6) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreScanCollectionItemRecord
     */
    constructor(id: UUID, appId: UUID, collectionId: UUID, scanRecordId: UUID, createdAt: Instant? = null, updatedAt: Instant? = null, deletedAt: Instant? = null): this() {
        this.id = id
        this.appId = appId
        this.collectionId = collectionId
        this.scanRecordId = scanRecordId
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.deletedAt = deletedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised CoreScanCollectionItemRecord
     */
    constructor(value: com.ifmix.api.core.jooq.tables.pojos.CoreScanCollectionItem?): this() {
        if (value != null) {
            this.id = value.id
            this.appId = value.appId
            this.collectionId = value.collectionId
            this.scanRecordId = value.scanRecordId
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.deletedAt = value.deletedAt
            resetTouchedOnNotNull()
        }
    }
}
