/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreScanCollection

import java.time.Instant
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreScanCollectionRecord private constructor() : UpdatableRecordImpl<CoreScanCollectionRecord>(CoreScanCollection.CORE_SCAN_COLLECTION) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var appId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var installId: UUID?
        set(value): Unit = set(2, value)
        get(): UUID? = get(2) as UUID?

    open var userId: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDefault")
    open var isDefault: Boolean?
        set(value): Unit = set(4, value)
        get(): Boolean? = get(4) as Boolean?

    open var createdAt: Instant?
        set(value): Unit = set(5, value)
        get(): Instant? = get(5) as Instant?

    open var updatedAt: Instant?
        set(value): Unit = set(6, value)
        get(): Instant? = get(6) as Instant?

    open var deletedAt: Instant?
        set(value): Unit = set(7, value)
        get(): Instant? = get(7) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreScanCollectionRecord
     */
    constructor(id: UUID, appId: UUID, installId: UUID? = null, userId: String? = null, isDefault: Boolean? = null, createdAt: Instant? = null, updatedAt: Instant? = null, deletedAt: Instant? = null): this() {
        this.id = id
        this.appId = appId
        this.installId = installId
        this.userId = userId
        this.isDefault = isDefault
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.deletedAt = deletedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised CoreScanCollectionRecord
     */
    constructor(value: com.ifmix.api.core.jooq.tables.pojos.CoreScanCollection?): this() {
        if (value != null) {
            this.id = value.id
            this.appId = value.appId
            this.installId = value.installId
            this.userId = value.userId
            this.isDefault = value.isDefault
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.deletedAt = value.deletedAt
            resetTouchedOnNotNull()
        }
    }
}
