/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreAuthProviderIdentity

import java.time.Instant
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAuthProviderIdentityRecord private constructor() : UpdatableRecordImpl<CoreAuthProviderIdentityRecord>(CoreAuthProviderIdentity.CORE_AUTH_PROVIDER_IDENTITY) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var authTenantId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var authIdentityId: UUID
        set(value): Unit = set(2, value)
        get(): UUID = get(2) as UUID

    open var provider: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var providerAccountId: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    open var email: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var emailVerified: Boolean?
        set(value): Unit = set(6, value)
        get(): Boolean? = get(6) as Boolean?

    open var phone: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var userMetadata: JSONB?
        set(value): Unit = set(8, value)
        get(): JSONB? = get(8) as JSONB?

    open var providerMetadata: JSONB?
        set(value): Unit = set(9, value)
        get(): JSONB? = get(9) as JSONB?

    open var loginIp: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var loginInstallId: UUID?
        set(value): Unit = set(11, value)
        get(): UUID? = get(11) as UUID?

    open var loginAppId: UUID?
        set(value): Unit = set(12, value)
        get(): UUID? = get(12) as UUID?

    open var createdAt: Instant?
        set(value): Unit = set(13, value)
        get(): Instant? = get(13) as Instant?

    open var updatedAt: Instant?
        set(value): Unit = set(14, value)
        get(): Instant? = get(14) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreAuthProviderIdentityRecord
     */
    constructor(id: UUID, authTenantId: UUID, authIdentityId: UUID, provider: String, providerAccountId: String, email: String? = null, emailVerified: Boolean? = null, phone: String? = null, userMetadata: JSONB? = null, providerMetadata: JSONB? = null, loginIp: String? = null, loginInstallId: UUID? = null, loginAppId: UUID? = null, createdAt: Instant? = null, updatedAt: Instant? = null): this() {
        this.id = id
        this.authTenantId = authTenantId
        this.authIdentityId = authIdentityId
        this.provider = provider
        this.providerAccountId = providerAccountId
        this.email = email
        this.emailVerified = emailVerified
        this.phone = phone
        this.userMetadata = userMetadata
        this.providerMetadata = providerMetadata
        this.loginIp = loginIp
        this.loginInstallId = loginInstallId
        this.loginAppId = loginAppId
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised CoreAuthProviderIdentityRecord
     */
    constructor(value: com.ifmix.api.core.jooq.tables.pojos.CoreAuthProviderIdentity?): this() {
        if (value != null) {
            this.id = value.id
            this.authTenantId = value.authTenantId
            this.authIdentityId = value.authIdentityId
            this.provider = value.provider
            this.providerAccountId = value.providerAccountId
            this.email = value.email
            this.emailVerified = value.emailVerified
            this.phone = value.phone
            this.userMetadata = value.userMetadata
            this.providerMetadata = value.providerMetadata
            this.loginIp = value.loginIp
            this.loginInstallId = value.loginInstallId
            this.loginAppId = value.loginAppId
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            resetTouchedOnNotNull()
        }
    }
}
