/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreUserInstallBinding

import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreUserInstallBindingRecord private constructor() : UpdatableRecordImpl<CoreUserInstallBindingRecord>(CoreUserInstallBinding.CORE_USER_INSTALL_BINDING) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var appId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var userId: UUID
        set(value): Unit = set(2, value)
        get(): UUID = get(2) as UUID

    open var installId: UUID
        set(value): Unit = set(3, value)
        get(): UUID = get(3) as UUID

    open var firstSeenAt: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    open var lastSeenAt: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open var loginCount: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var clientIp: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var clientPlatform: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(9, value)
        get(): OffsetDateTime? = get(9) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(10, value)
        get(): OffsetDateTime? = get(10) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreUserInstallBindingRecord
     */
    constructor(id: UUID, appId: UUID, userId: UUID, installId: UUID, firstSeenAt: OffsetDateTime? = null, lastSeenAt: OffsetDateTime? = null, loginCount: Int? = null, clientIp: String? = null, clientPlatform: String? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.appId = appId
        this.userId = userId
        this.installId = installId
        this.firstSeenAt = firstSeenAt
        this.lastSeenAt = lastSeenAt
        this.loginCount = loginCount
        this.clientIp = clientIp
        this.clientPlatform = clientPlatform
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
