/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreAuthTenant

import java.time.Instant
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAuthTenantRecord private constructor() : UpdatableRecordImpl<CoreAuthTenantRecord>(CoreAuthTenant.CORE_AUTH_TENANT) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var jwtPrivateKeyPem: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var jwtIssuer: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var createdAt: Instant?
        set(value): Unit = set(3, value)
        get(): Instant? = get(3) as Instant?

    open var updatedAt: Instant?
        set(value): Unit = set(4, value)
        get(): Instant? = get(4) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreAuthTenantRecord
     */
    constructor(id: UUID, jwtPrivateKeyPem: String? = null, jwtIssuer: String? = null, createdAt: Instant? = null, updatedAt: Instant? = null): this() {
        this.id = id
        this.jwtPrivateKeyPem = jwtPrivateKeyPem
        this.jwtIssuer = jwtIssuer
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised CoreAuthTenantRecord
     */
    constructor(value: com.ifmix.api.core.jooq.tables.pojos.CoreAuthTenant?): this() {
        if (value != null) {
            this.id = value.id
            this.jwtPrivateKeyPem = value.jwtPrivateKeyPem
            this.jwtIssuer = value.jwtIssuer
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            resetTouchedOnNotNull()
        }
    }
}
