/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreAppRefreshToken

import java.time.Instant
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAppRefreshTokenRecord private constructor() : UpdatableRecordImpl<CoreAppRefreshTokenRecord>(CoreAppRefreshToken.CORE_APP_REFRESH_TOKEN) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var appId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var appUserId: UUID
        set(value): Unit = set(2, value)
        get(): UUID = get(2) as UUID

    open var deviceSecretId: UUID?
        set(value): Unit = set(3, value)
        get(): UUID? = get(3) as UUID?

    open var tokenHash: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    open var loginInstallId: UUID?
        set(value): Unit = set(5, value)
        get(): UUID? = get(5) as UUID?

    open var expiresAt: Instant?
        set(value): Unit = set(6, value)
        get(): Instant? = get(6) as Instant?

    open var revokedAt: Instant?
        set(value): Unit = set(7, value)
        get(): Instant? = get(7) as Instant?

    open var replacedBy: UUID?
        set(value): Unit = set(8, value)
        get(): UUID? = get(8) as UUID?

    open var createdAt: Instant?
        set(value): Unit = set(9, value)
        get(): Instant? = get(9) as Instant?

    open var updatedAt: Instant?
        set(value): Unit = set(10, value)
        get(): Instant? = get(10) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreAppRefreshTokenRecord
     */
    constructor(id: UUID, appId: UUID, appUserId: UUID, deviceSecretId: UUID? = null, tokenHash: String, loginInstallId: UUID? = null, expiresAt: Instant? = null, revokedAt: Instant? = null, replacedBy: UUID? = null, createdAt: Instant? = null, updatedAt: Instant? = null): this() {
        this.id = id
        this.appId = appId
        this.appUserId = appUserId
        this.deviceSecretId = deviceSecretId
        this.tokenHash = tokenHash
        this.loginInstallId = loginInstallId
        this.expiresAt = expiresAt
        this.revokedAt = revokedAt
        this.replacedBy = replacedBy
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised CoreAppRefreshTokenRecord
     */
    constructor(value: com.ifmix.api.core.jooq.tables.pojos.CoreAppRefreshToken?): this() {
        if (value != null) {
            this.id = value.id
            this.appId = value.appId
            this.appUserId = value.appUserId
            this.deviceSecretId = value.deviceSecretId
            this.tokenHash = value.tokenHash
            this.loginInstallId = value.loginInstallId
            this.expiresAt = value.expiresAt
            this.revokedAt = value.revokedAt
            this.replacedBy = value.replacedBy
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            resetTouchedOnNotNull()
        }
    }
}
