/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreScanCollectionItem

import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreScanCollectionItemRecord private constructor() : UpdatableRecordImpl<CoreScanCollectionItemRecord>(CoreScanCollectionItem.CORE_SCAN_COLLECTION_ITEM) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var appId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var collectionId: UUID
        set(value): Unit = set(2, value)
        get(): UUID = get(2) as UUID

    open var scanRecordId: UUID
        set(value): Unit = set(3, value)
        get(): UUID = get(3) as UUID

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open var deletedAt: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreScanCollectionItemRecord
     */
    constructor(id: UUID, appId: UUID, collectionId: UUID, scanRecordId: UUID, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null, deletedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.appId = appId
        this.collectionId = collectionId
        this.scanRecordId = scanRecordId
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.deletedAt = deletedAt
        resetTouchedOnNotNull()
    }
}
