/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreAppRefreshToken

import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAppRefreshTokenRecord private constructor() : UpdatableRecordImpl<CoreAppRefreshTokenRecord>(CoreAppRefreshToken.CORE_APP_REFRESH_TOKEN) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var appId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var appUserId: UUID
        set(value): Unit = set(2, value)
        get(): UUID = get(2) as UUID

    open var deviceSecretId: UUID?
        set(value): Unit = set(3, value)
        get(): UUID? = get(3) as UUID?

    open var tokenHash: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    open var loginInstallId: UUID?
        set(value): Unit = set(5, value)
        get(): UUID? = get(5) as UUID?

    open var expiresAt: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var revokedAt: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    open var replacedBy: UUID?
        set(value): Unit = set(8, value)
        get(): UUID? = get(8) as UUID?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(9, value)
        get(): OffsetDateTime? = get(9) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(10, value)
        get(): OffsetDateTime? = get(10) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreAppRefreshTokenRecord
     */
    constructor(id: UUID, appId: UUID, appUserId: UUID, deviceSecretId: UUID? = null, tokenHash: String, loginInstallId: UUID? = null, expiresAt: OffsetDateTime? = null, revokedAt: OffsetDateTime? = null, replacedBy: UUID? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.appId = appId
        this.appUserId = appUserId
        this.deviceSecretId = deviceSecretId
        this.tokenHash = tokenHash
        this.loginInstallId = loginInstallId
        this.expiresAt = expiresAt
        this.revokedAt = revokedAt
        this.replacedBy = replacedBy
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
