/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables.records


import com.ifmix.api.core.jooq.tables.CoreSubscription

import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreSubscriptionRecord private constructor() : UpdatableRecordImpl<CoreSubscriptionRecord>(CoreSubscription.CORE_SUBSCRIPTION) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var appId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var subscriptionPxid: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var originalTransactionId: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var productId: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var platform: Short?
        set(value): Unit = set(5, value)
        get(): Short? = get(5) as Short?

    open var active: Boolean?
        set(value): Unit = set(6, value)
        get(): Boolean? = get(6) as Boolean?

    open var subStatus: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var expiryDate: OffsetDateTime?
        set(value): Unit = set(8, value)
        get(): OffsetDateTime? = get(8) as OffsetDateTime?

    open var purchaseToken: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var rawResponse: JSONB?
        set(value): Unit = set(10, value)
        get(): JSONB? = get(10) as JSONB?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(11, value)
        get(): OffsetDateTime? = get(11) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(12, value)
        get(): OffsetDateTime? = get(12) as OffsetDateTime?

    open var deletedAt: OffsetDateTime?
        set(value): Unit = set(13, value)
        get(): OffsetDateTime? = get(13) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CoreSubscriptionRecord
     */
    constructor(id: UUID, appId: UUID, subscriptionPxid: String? = null, originalTransactionId: String? = null, productId: String? = null, platform: Short? = null, active: Boolean? = null, subStatus: String? = null, expiryDate: OffsetDateTime? = null, purchaseToken: String? = null, rawResponse: JSONB? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null, deletedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.appId = appId
        this.subscriptionPxid = subscriptionPxid
        this.originalTransactionId = originalTransactionId
        this.productId = productId
        this.platform = platform
        this.active = active
        this.subStatus = subStatus
        this.expiryDate = expiryDate
        this.purchaseToken = purchaseToken
        this.rawResponse = rawResponse
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.deletedAt = deletedAt
        resetTouchedOnNotNull()
    }
}
