extend type Mutation {
    # Admin batch
    todo_batchDelete(ids: [ID!]!): OperationResult! @requirePermission(permission: "todo:batch")
    todo_batchUpdate(patches: [BatchUpdateTodoInput!]!): OperationResult! @requirePermission(permission: "todo:batch")
    todoItem_batchDelete(ids: [ID!]!): OperationResult! @requirePermission(permission: "todo:batch")

    # AppConfig
    appConfig_createRevision(input: CreateAppConfigRevisionInput!): AppConfigRevision! @requirePermission(permission: "appconfig:write")
    appConfig_toggleRevision(id: ID!, enabled: Boolean!): AppConfigRevision! @requirePermission(permission: "appconfig:write")
}
