extend type Mutation {
    # Admin batch
    mutation_demo_batchDeleteTodos(ids: [ID!]!): OperationResult! @requirePermission(permission: "todo:batch")
    mutation_demo_batchUpdateTodos(patches: [BatchUpdateTodoInput!]!): OperationResult! @requirePermission(permission: "todo:batch")
    mutation_demo_batchDeleteTodoItems(ids: [ID!]!): OperationResult! @requirePermission(permission: "todo:batch")

    # AppConfig
    mutation_app_createConfigRevision(input: CreateAppConfigRevisionInput!): AppConfigRevision! @requirePermission(permission: "appconfig:write")
    mutation_app_toggleConfigRevision(id: ID!, enabled: Boolean!): AppConfigRevision! @requirePermission(permission: "appconfig:write")
}
