/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables


import com.ifmix.api.core.jooq.Public
import com.ifmix.api.core.jooq.indexes.APP_INFO_SLUG_UQ
import com.ifmix.api.core.jooq.keys.APP_INFO_PKEY
import com.ifmix.api.core.jooq.tables.records.CoreAppInfoRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAppInfo(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoreAppInfoRecord>?,
    parentPath: InverseForeignKey<out Record, CoreAppInfoRecord>?,
    aliased: Table<CoreAppInfoRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoreAppInfoRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.core_app_info</code>
         */
        val CORE_APP_INFO: CoreAppInfo = CoreAppInfo()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoreAppInfoRecord> = CoreAppInfoRecord::class.java

    /**
     * The column <code>public.core_app_info.id</code>.
     */
    val ID: TableField<CoreAppInfoRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_app_info.name</code>.
     */
    val NAME: TableField<CoreAppInfoRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.core_app_info.description</code>.
     */
    val DESCRIPTION: TableField<CoreAppInfoRecord, String?> = createField(DSL.name("description"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.core_app_info.slug</code>.
     */
    val SLUG: TableField<CoreAppInfoRecord, String?> = createField(DSL.name("slug"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.core_app_info.created_at</code>.
     */
    val CREATED_AT: TableField<CoreAppInfoRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_app_info.updated_at</code>.
     */
    val UPDATED_AT: TableField<CoreAppInfoRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<CoreAppInfoRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoreAppInfoRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoreAppInfoRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.core_app_info</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.core_app_info</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.core_app_info</code> table reference
     */
    constructor(): this(DSL.name("core_app_info"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(APP_INFO_SLUG_UQ)
    override fun getPrimaryKey(): UniqueKey<CoreAppInfoRecord> = APP_INFO_PKEY
    override fun `as`(alias: String): CoreAppInfo = CoreAppInfo(DSL.name(alias), this)
    override fun `as`(alias: Name): CoreAppInfo = CoreAppInfo(alias, this)
    override fun `as`(alias: Table<*>): CoreAppInfo = CoreAppInfo(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CoreAppInfo = CoreAppInfo(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CoreAppInfo = CoreAppInfo(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CoreAppInfo = CoreAppInfo(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CoreAppInfo = CoreAppInfo(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CoreAppInfo = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CoreAppInfo = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CoreAppInfo = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CoreAppInfo = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CoreAppInfo = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CoreAppInfo = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CoreAppInfo = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): CoreAppInfo = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): CoreAppInfo = where(DSL.notExists(select))
}
