/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables


import com.ifmix.api.core.jooq.Public
import com.ifmix.api.core.jooq.keys.AUTH_TENANT_PKEY
import com.ifmix.api.core.jooq.keys.CORE_AUTH_DEVICE_SECRET__AUTH_DEVICE_SECRET_AUTH_TENANT_ID_FKEY
import com.ifmix.api.core.jooq.keys.CORE_AUTH_IDENTITY__AUTH_IDENTITY_AUTH_TENANT_ID_FKEY
import com.ifmix.api.core.jooq.keys.CORE_AUTH_PROVIDER_IDENTITY__AUTH_PROVIDER_IDENTITY_AUTH_TENANT_ID_FKEY
import com.ifmix.api.core.jooq.tables.CoreAuthDeviceSecret.CoreAuthDeviceSecretPath
import com.ifmix.api.core.jooq.tables.CoreAuthIdentity.CoreAuthIdentityPath
import com.ifmix.api.core.jooq.tables.CoreAuthProviderIdentity.CoreAuthProviderIdentityPath
import com.ifmix.api.core.jooq.tables.records.CoreAuthTenantRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAuthTenant(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoreAuthTenantRecord>?,
    parentPath: InverseForeignKey<out Record, CoreAuthTenantRecord>?,
    aliased: Table<CoreAuthTenantRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoreAuthTenantRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.core_auth_tenant</code>
         */
        val CORE_AUTH_TENANT: CoreAuthTenant = CoreAuthTenant()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoreAuthTenantRecord> = CoreAuthTenantRecord::class.java

    /**
     * The column <code>public.core_auth_tenant.id</code>.
     */
    val ID: TableField<CoreAuthTenantRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_auth_tenant.jwt_private_key_pem</code>.
     */
    val JWT_PRIVATE_KEY_PEM: TableField<CoreAuthTenantRecord, String?> = createField(DSL.name("jwt_private_key_pem"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.core_auth_tenant.jwt_issuer</code>.
     */
    val JWT_ISSUER: TableField<CoreAuthTenantRecord, String?> = createField(DSL.name("jwt_issuer"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.core_auth_tenant.created_at</code>.
     */
    val CREATED_AT: TableField<CoreAuthTenantRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_auth_tenant.updated_at</code>.
     */
    val UPDATED_AT: TableField<CoreAuthTenantRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<CoreAuthTenantRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoreAuthTenantRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoreAuthTenantRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.core_auth_tenant</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.core_auth_tenant</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.core_auth_tenant</code> table reference
     */
    constructor(): this(DSL.name("core_auth_tenant"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreAuthTenantRecord>?, parentPath: InverseForeignKey<out Record, CoreAuthTenantRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CORE_AUTH_TENANT, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CoreAuthTenantPath : CoreAuthTenant, Path<CoreAuthTenantRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreAuthTenantRecord>?, parentPath: InverseForeignKey<out Record, CoreAuthTenantRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CoreAuthTenantRecord>): super(alias, aliased)
        override fun `as`(alias: String): CoreAuthTenantPath = CoreAuthTenantPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CoreAuthTenantPath = CoreAuthTenantPath(alias, this)
        override fun `as`(alias: Table<*>): CoreAuthTenantPath = CoreAuthTenantPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<CoreAuthTenantRecord> = AUTH_TENANT_PKEY

    private lateinit var _coreAuthDeviceSecret: CoreAuthDeviceSecretPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.core_auth_device_secret</code> table
     */
    fun coreAuthDeviceSecret(): CoreAuthDeviceSecretPath {
        if (!this::_coreAuthDeviceSecret.isInitialized)
            _coreAuthDeviceSecret = CoreAuthDeviceSecretPath(this, null, CORE_AUTH_DEVICE_SECRET__AUTH_DEVICE_SECRET_AUTH_TENANT_ID_FKEY.inverseKey)

        return _coreAuthDeviceSecret;
    }

    val coreAuthDeviceSecret: CoreAuthDeviceSecretPath
        get(): CoreAuthDeviceSecretPath = coreAuthDeviceSecret()

    private lateinit var _coreAuthIdentity: CoreAuthIdentityPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.core_auth_identity</code> table
     */
    fun coreAuthIdentity(): CoreAuthIdentityPath {
        if (!this::_coreAuthIdentity.isInitialized)
            _coreAuthIdentity = CoreAuthIdentityPath(this, null, CORE_AUTH_IDENTITY__AUTH_IDENTITY_AUTH_TENANT_ID_FKEY.inverseKey)

        return _coreAuthIdentity;
    }

    val coreAuthIdentity: CoreAuthIdentityPath
        get(): CoreAuthIdentityPath = coreAuthIdentity()

    private lateinit var _coreAuthProviderIdentity: CoreAuthProviderIdentityPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.core_auth_provider_identity</code> table
     */
    fun coreAuthProviderIdentity(): CoreAuthProviderIdentityPath {
        if (!this::_coreAuthProviderIdentity.isInitialized)
            _coreAuthProviderIdentity = CoreAuthProviderIdentityPath(this, null, CORE_AUTH_PROVIDER_IDENTITY__AUTH_PROVIDER_IDENTITY_AUTH_TENANT_ID_FKEY.inverseKey)

        return _coreAuthProviderIdentity;
    }

    val coreAuthProviderIdentity: CoreAuthProviderIdentityPath
        get(): CoreAuthProviderIdentityPath = coreAuthProviderIdentity()
    override fun `as`(alias: String): CoreAuthTenant = CoreAuthTenant(DSL.name(alias), this)
    override fun `as`(alias: Name): CoreAuthTenant = CoreAuthTenant(alias, this)
    override fun `as`(alias: Table<*>): CoreAuthTenant = CoreAuthTenant(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CoreAuthTenant = CoreAuthTenant(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CoreAuthTenant = CoreAuthTenant(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CoreAuthTenant = CoreAuthTenant(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CoreAuthTenant = CoreAuthTenant(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CoreAuthTenant = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CoreAuthTenant = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CoreAuthTenant = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CoreAuthTenant = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CoreAuthTenant = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CoreAuthTenant = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CoreAuthTenant = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): CoreAuthTenant = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): CoreAuthTenant = where(DSL.notExists(select))
}
