/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables


import com.ifmix.api.core.infra.jooq.InstantConverter
import com.ifmix.api.core.jooq.Public
import com.ifmix.api.core.jooq.indexes.COLLECTION_APP_ID_IDX
import com.ifmix.api.core.jooq.indexes.COLLECTION_DEFAULT_UQ
import com.ifmix.api.core.jooq.indexes.COLLECTION_INSTALL_ID_IDX
import com.ifmix.api.core.jooq.keys.COLLECTION_PKEY
import com.ifmix.api.core.jooq.keys.CORE_SCAN_COLLECTION_ITEM__COLLECTION_ITEM_COLLECTION_ID_FKEY
import com.ifmix.api.core.jooq.tables.CoreScanCollectionItem.CoreScanCollectionItemPath
import com.ifmix.api.core.jooq.tables.records.CoreScanCollectionRecord

import java.time.Instant
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreScanCollection(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoreScanCollectionRecord>?,
    parentPath: InverseForeignKey<out Record, CoreScanCollectionRecord>?,
    aliased: Table<CoreScanCollectionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoreScanCollectionRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.core_scan_collection</code>
         */
        val CORE_SCAN_COLLECTION: CoreScanCollection = CoreScanCollection()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoreScanCollectionRecord> = CoreScanCollectionRecord::class.java

    /**
     * The column <code>public.core_scan_collection.id</code>.
     */
    val ID: TableField<CoreScanCollectionRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_scan_collection.app_id</code>.
     */
    val APP_ID: TableField<CoreScanCollectionRecord, UUID?> = createField(DSL.name("app_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_scan_collection.install_id</code>.
     */
    val INSTALL_ID: TableField<CoreScanCollectionRecord, UUID?> = createField(DSL.name("install_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.core_scan_collection.user_id</code>.
     */
    val USER_ID: TableField<CoreScanCollectionRecord, String?> = createField(DSL.name("user_id"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.core_scan_collection.is_default</code>.
     */
    val IS_DEFAULT: TableField<CoreScanCollectionRecord, Boolean?> = createField(DSL.name("is_default"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.core_scan_collection.created_at</code>.
     */
    val CREATED_AT: TableField<CoreScanCollectionRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", InstantConverter())

    /**
     * The column <code>public.core_scan_collection.updated_at</code>.
     */
    val UPDATED_AT: TableField<CoreScanCollectionRecord, Instant?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", InstantConverter())

    /**
     * The column <code>public.core_scan_collection.deleted_at</code>.
     */
    val DELETED_AT: TableField<CoreScanCollectionRecord, Instant?> = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", InstantConverter())

    private constructor(alias: Name, aliased: Table<CoreScanCollectionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoreScanCollectionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoreScanCollectionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.core_scan_collection</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.core_scan_collection</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.core_scan_collection</code> table reference
     */
    constructor(): this(DSL.name("core_scan_collection"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreScanCollectionRecord>?, parentPath: InverseForeignKey<out Record, CoreScanCollectionRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CORE_SCAN_COLLECTION, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CoreScanCollectionPath : CoreScanCollection, Path<CoreScanCollectionRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreScanCollectionRecord>?, parentPath: InverseForeignKey<out Record, CoreScanCollectionRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CoreScanCollectionRecord>): super(alias, aliased)
        override fun `as`(alias: String): CoreScanCollectionPath = CoreScanCollectionPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CoreScanCollectionPath = CoreScanCollectionPath(alias, this)
        override fun `as`(alias: Table<*>): CoreScanCollectionPath = CoreScanCollectionPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(COLLECTION_APP_ID_IDX, COLLECTION_DEFAULT_UQ, COLLECTION_INSTALL_ID_IDX)
    override fun getPrimaryKey(): UniqueKey<CoreScanCollectionRecord> = COLLECTION_PKEY

    private lateinit var _coreScanCollectionItem: CoreScanCollectionItemPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.core_scan_collection_item</code> table
     */
    fun coreScanCollectionItem(): CoreScanCollectionItemPath {
        if (!this::_coreScanCollectionItem.isInitialized)
            _coreScanCollectionItem = CoreScanCollectionItemPath(this, null, CORE_SCAN_COLLECTION_ITEM__COLLECTION_ITEM_COLLECTION_ID_FKEY.inverseKey)

        return _coreScanCollectionItem;
    }

    val coreScanCollectionItem: CoreScanCollectionItemPath
        get(): CoreScanCollectionItemPath = coreScanCollectionItem()
    override fun `as`(alias: String): CoreScanCollection = CoreScanCollection(DSL.name(alias), this)
    override fun `as`(alias: Name): CoreScanCollection = CoreScanCollection(alias, this)
    override fun `as`(alias: Table<*>): CoreScanCollection = CoreScanCollection(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CoreScanCollection = CoreScanCollection(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CoreScanCollection = CoreScanCollection(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CoreScanCollection = CoreScanCollection(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CoreScanCollection = CoreScanCollection(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CoreScanCollection = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CoreScanCollection = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CoreScanCollection = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CoreScanCollection = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CoreScanCollection = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CoreScanCollection = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CoreScanCollection = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): CoreScanCollection = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): CoreScanCollection = where(DSL.notExists(select))
}
