/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables


import com.ifmix.api.core.jooq.Public
import com.ifmix.api.core.jooq.indexes.DEVICE_SECRET_IDENTITY_IDX
import com.ifmix.api.core.jooq.indexes.DEVICE_SECRET_UQ
import com.ifmix.api.core.jooq.keys.AUTH_DEVICE_SECRET_PKEY
import com.ifmix.api.core.jooq.keys.CORE_APP_REFRESH_TOKEN__APP_REFRESH_TOKEN_DEVICE_SECRET_ID_FKEY
import com.ifmix.api.core.jooq.keys.CORE_AUTH_DEVICE_SECRET__AUTH_DEVICE_SECRET_AUTH_IDENTITY_ID_FKEY
import com.ifmix.api.core.jooq.keys.CORE_AUTH_DEVICE_SECRET__AUTH_DEVICE_SECRET_AUTH_TENANT_ID_FKEY
import com.ifmix.api.core.jooq.tables.CoreAppRefreshToken.CoreAppRefreshTokenPath
import com.ifmix.api.core.jooq.tables.CoreAuthIdentity.CoreAuthIdentityPath
import com.ifmix.api.core.jooq.tables.CoreAuthTenant.CoreAuthTenantPath
import com.ifmix.api.core.jooq.tables.records.CoreAuthDeviceSecretRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAuthDeviceSecret(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoreAuthDeviceSecretRecord>?,
    parentPath: InverseForeignKey<out Record, CoreAuthDeviceSecretRecord>?,
    aliased: Table<CoreAuthDeviceSecretRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoreAuthDeviceSecretRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.core_auth_device_secret</code>
         */
        val CORE_AUTH_DEVICE_SECRET: CoreAuthDeviceSecret = CoreAuthDeviceSecret()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoreAuthDeviceSecretRecord> = CoreAuthDeviceSecretRecord::class.java

    /**
     * The column <code>public.core_auth_device_secret.id</code>.
     */
    val ID: TableField<CoreAuthDeviceSecretRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_auth_device_secret.auth_tenant_id</code>.
     */
    val AUTH_TENANT_ID: TableField<CoreAuthDeviceSecretRecord, UUID?> = createField(DSL.name("auth_tenant_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_auth_device_secret.auth_identity_id</code>.
     */
    val AUTH_IDENTITY_ID: TableField<CoreAuthDeviceSecretRecord, UUID?> = createField(DSL.name("auth_identity_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_auth_device_secret.secret_hash</code>.
     */
    val SECRET_HASH: TableField<CoreAuthDeviceSecretRecord, String?> = createField(DSL.name("secret_hash"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.core_auth_device_secret.login_install_id</code>.
     */
    val LOGIN_INSTALL_ID: TableField<CoreAuthDeviceSecretRecord, UUID?> = createField(DSL.name("login_install_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.core_auth_device_secret.expires_at</code>.
     */
    val EXPIRES_AT: TableField<CoreAuthDeviceSecretRecord, OffsetDateTime?> = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.core_auth_device_secret.revoked_at</code>.
     */
    val REVOKED_AT: TableField<CoreAuthDeviceSecretRecord, OffsetDateTime?> = createField(DSL.name("revoked_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.core_auth_device_secret.last_used_at</code>.
     */
    val LAST_USED_AT: TableField<CoreAuthDeviceSecretRecord, OffsetDateTime?> = createField(DSL.name("last_used_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.core_auth_device_secret.created_at</code>.
     */
    val CREATED_AT: TableField<CoreAuthDeviceSecretRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_auth_device_secret.updated_at</code>.
     */
    val UPDATED_AT: TableField<CoreAuthDeviceSecretRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<CoreAuthDeviceSecretRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoreAuthDeviceSecretRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoreAuthDeviceSecretRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.core_auth_device_secret</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.core_auth_device_secret</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.core_auth_device_secret</code> table reference
     */
    constructor(): this(DSL.name("core_auth_device_secret"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreAuthDeviceSecretRecord>?, parentPath: InverseForeignKey<out Record, CoreAuthDeviceSecretRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CORE_AUTH_DEVICE_SECRET, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CoreAuthDeviceSecretPath : CoreAuthDeviceSecret, Path<CoreAuthDeviceSecretRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreAuthDeviceSecretRecord>?, parentPath: InverseForeignKey<out Record, CoreAuthDeviceSecretRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CoreAuthDeviceSecretRecord>): super(alias, aliased)
        override fun `as`(alias: String): CoreAuthDeviceSecretPath = CoreAuthDeviceSecretPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CoreAuthDeviceSecretPath = CoreAuthDeviceSecretPath(alias, this)
        override fun `as`(alias: Table<*>): CoreAuthDeviceSecretPath = CoreAuthDeviceSecretPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(DEVICE_SECRET_IDENTITY_IDX, DEVICE_SECRET_UQ)
    override fun getPrimaryKey(): UniqueKey<CoreAuthDeviceSecretRecord> = AUTH_DEVICE_SECRET_PKEY
    override fun getReferences(): List<ForeignKey<CoreAuthDeviceSecretRecord, *>> = listOf(CORE_AUTH_DEVICE_SECRET__AUTH_DEVICE_SECRET_AUTH_IDENTITY_ID_FKEY, CORE_AUTH_DEVICE_SECRET__AUTH_DEVICE_SECRET_AUTH_TENANT_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.core_auth_identity</code>
     * table.
     */
    fun coreAuthIdentity(): CoreAuthIdentityPath = coreAuthIdentity
    val coreAuthIdentity: CoreAuthIdentityPath by lazy { CoreAuthIdentityPath(this, CORE_AUTH_DEVICE_SECRET__AUTH_DEVICE_SECRET_AUTH_IDENTITY_ID_FKEY, null) }

    /**
     * Get the implicit join path to the <code>public.core_auth_tenant</code>
     * table.
     */
    fun coreAuthTenant(): CoreAuthTenantPath = coreAuthTenant
    val coreAuthTenant: CoreAuthTenantPath by lazy { CoreAuthTenantPath(this, CORE_AUTH_DEVICE_SECRET__AUTH_DEVICE_SECRET_AUTH_TENANT_ID_FKEY, null) }

    private lateinit var _coreAppRefreshToken: CoreAppRefreshTokenPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.core_app_refresh_token</code> table
     */
    fun coreAppRefreshToken(): CoreAppRefreshTokenPath {
        if (!this::_coreAppRefreshToken.isInitialized)
            _coreAppRefreshToken = CoreAppRefreshTokenPath(this, null, CORE_APP_REFRESH_TOKEN__APP_REFRESH_TOKEN_DEVICE_SECRET_ID_FKEY.inverseKey)

        return _coreAppRefreshToken;
    }

    val coreAppRefreshToken: CoreAppRefreshTokenPath
        get(): CoreAppRefreshTokenPath = coreAppRefreshToken()
    override fun `as`(alias: String): CoreAuthDeviceSecret = CoreAuthDeviceSecret(DSL.name(alias), this)
    override fun `as`(alias: Name): CoreAuthDeviceSecret = CoreAuthDeviceSecret(alias, this)
    override fun `as`(alias: Table<*>): CoreAuthDeviceSecret = CoreAuthDeviceSecret(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CoreAuthDeviceSecret = CoreAuthDeviceSecret(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CoreAuthDeviceSecret = CoreAuthDeviceSecret(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CoreAuthDeviceSecret = CoreAuthDeviceSecret(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CoreAuthDeviceSecret = CoreAuthDeviceSecret(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CoreAuthDeviceSecret = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CoreAuthDeviceSecret = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CoreAuthDeviceSecret = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CoreAuthDeviceSecret = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CoreAuthDeviceSecret = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CoreAuthDeviceSecret = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CoreAuthDeviceSecret = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): CoreAuthDeviceSecret = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): CoreAuthDeviceSecret = where(DSL.notExists(select))
}
