/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables


import com.ifmix.api.core.jooq.Public
import com.ifmix.api.core.jooq.indexes.SCAN_RECORD_APP_ID_IDX
import com.ifmix.api.core.jooq.keys.CORE_SCAN_COLLECTION_ITEM__COLLECTION_ITEM_SCAN_RECORD_ID_FKEY
import com.ifmix.api.core.jooq.keys.SCAN_RECORD_PKEY
import com.ifmix.api.core.jooq.tables.CoreScanCollectionItem.CoreScanCollectionItemPath
import com.ifmix.api.core.jooq.tables.records.CoreScanRecordRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreScanRecord(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoreScanRecordRecord>?,
    parentPath: InverseForeignKey<out Record, CoreScanRecordRecord>?,
    aliased: Table<CoreScanRecordRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoreScanRecordRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.core_scan_record</code>
         */
        val CORE_SCAN_RECORD: CoreScanRecord = CoreScanRecord()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoreScanRecordRecord> = CoreScanRecordRecord::class.java

    /**
     * The column <code>public.core_scan_record.id</code>.
     */
    val ID: TableField<CoreScanRecordRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_scan_record.app_id</code>.
     */
    val APP_ID: TableField<CoreScanRecordRecord, UUID?> = createField(DSL.name("app_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_scan_record.result_json</code>.
     */
    val RESULT_JSON: TableField<CoreScanRecordRecord, JSONB?> = createField(DSL.name("result_json"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.core_scan_record.status</code>.
     */
    val STATUS: TableField<CoreScanRecordRecord, Short?> = createField(DSL.name("status"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("100"), SQLDataType.SMALLINT)), this, "")

    /**
     * The column <code>public.core_scan_record.client_ip</code>.
     */
    val CLIENT_IP: TableField<CoreScanRecordRecord, String?> = createField(DSL.name("client_ip"), SQLDataType.VARCHAR(45), this, "")

    /**
     * The column <code>public.core_scan_record.created_at</code>.
     */
    val CREATED_AT: TableField<CoreScanRecordRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_scan_record.updated_at</code>.
     */
    val UPDATED_AT: TableField<CoreScanRecordRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_scan_record.deleted_at</code>.
     */
    val DELETED_AT: TableField<CoreScanRecordRecord, OffsetDateTime?> = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.core_scan_record.image_keys</code>.
     */
    val IMAGE_KEYS: TableField<CoreScanRecordRecord, JSONB?> = createField(DSL.name("image_keys"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'[]'::jsonb"), SQLDataType.JSONB)), this, "")

    /**
     * The column <code>public.core_scan_record.user_display_name</code>.
     */
    val USER_DISPLAY_NAME: TableField<CoreScanRecordRecord, String?> = createField(DSL.name("user_display_name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.core_scan_record.user_notes</code>.
     */
    val USER_NOTES: TableField<CoreScanRecordRecord, String?> = createField(DSL.name("user_notes"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.core_scan_record.collected</code>.
     */
    val COLLECTED: TableField<CoreScanRecordRecord, Boolean?> = createField(DSL.name("collected"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.core_scan_record.lang</code>.
     */
    val LANG: TableField<CoreScanRecordRecord, String?> = createField(DSL.name("lang"), SQLDataType.VARCHAR(16), this, "")

    /**
     * The column <code>public.core_scan_record.country</code>.
     */
    val COUNTRY: TableField<CoreScanRecordRecord, String?> = createField(DSL.name("country"), SQLDataType.VARCHAR(8), this, "")

    /**
     * The column <code>public.core_scan_record.currency</code>.
     */
    val CURRENCY: TableField<CoreScanRecordRecord, String?> = createField(DSL.name("currency"), SQLDataType.VARCHAR(8), this, "")

    private constructor(alias: Name, aliased: Table<CoreScanRecordRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoreScanRecordRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoreScanRecordRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.core_scan_record</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.core_scan_record</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.core_scan_record</code> table reference
     */
    constructor(): this(DSL.name("core_scan_record"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreScanRecordRecord>?, parentPath: InverseForeignKey<out Record, CoreScanRecordRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CORE_SCAN_RECORD, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CoreScanRecordPath : CoreScanRecord, Path<CoreScanRecordRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreScanRecordRecord>?, parentPath: InverseForeignKey<out Record, CoreScanRecordRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CoreScanRecordRecord>): super(alias, aliased)
        override fun `as`(alias: String): CoreScanRecordPath = CoreScanRecordPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CoreScanRecordPath = CoreScanRecordPath(alias, this)
        override fun `as`(alias: Table<*>): CoreScanRecordPath = CoreScanRecordPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(SCAN_RECORD_APP_ID_IDX)
    override fun getPrimaryKey(): UniqueKey<CoreScanRecordRecord> = SCAN_RECORD_PKEY

    private lateinit var _coreScanCollectionItem: CoreScanCollectionItemPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.core_scan_collection_item</code> table
     */
    fun coreScanCollectionItem(): CoreScanCollectionItemPath {
        if (!this::_coreScanCollectionItem.isInitialized)
            _coreScanCollectionItem = CoreScanCollectionItemPath(this, null, CORE_SCAN_COLLECTION_ITEM__COLLECTION_ITEM_SCAN_RECORD_ID_FKEY.inverseKey)

        return _coreScanCollectionItem;
    }

    val coreScanCollectionItem: CoreScanCollectionItemPath
        get(): CoreScanCollectionItemPath = coreScanCollectionItem()
    override fun `as`(alias: String): CoreScanRecord = CoreScanRecord(DSL.name(alias), this)
    override fun `as`(alias: Name): CoreScanRecord = CoreScanRecord(alias, this)
    override fun `as`(alias: Table<*>): CoreScanRecord = CoreScanRecord(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CoreScanRecord = CoreScanRecord(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CoreScanRecord = CoreScanRecord(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CoreScanRecord = CoreScanRecord(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CoreScanRecord = CoreScanRecord(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CoreScanRecord = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CoreScanRecord = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CoreScanRecord = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CoreScanRecord = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CoreScanRecord = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CoreScanRecord = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CoreScanRecord = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): CoreScanRecord = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): CoreScanRecord = where(DSL.notExists(select))
}
