/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables


import com.ifmix.api.core.jooq.Public
import com.ifmix.api.core.jooq.indexes.COLLECTION_ITEM_APP_COLL_IDX
import com.ifmix.api.core.jooq.indexes.COLLECTION_ITEM_SCAN_RECORD_IDX
import com.ifmix.api.core.jooq.indexes.COLLECTION_ITEM_SCAN_UQ
import com.ifmix.api.core.jooq.keys.COLLECTION_ITEM_PKEY
import com.ifmix.api.core.jooq.keys.CORE_SCAN_COLLECTION_ITEM__COLLECTION_ITEM_COLLECTION_ID_FKEY
import com.ifmix.api.core.jooq.keys.CORE_SCAN_COLLECTION_ITEM__COLLECTION_ITEM_SCAN_RECORD_ID_FKEY
import com.ifmix.api.core.jooq.tables.CoreScanCollection.CoreScanCollectionPath
import com.ifmix.api.core.jooq.tables.CoreScanRecord.CoreScanRecordPath
import com.ifmix.api.core.jooq.tables.records.CoreScanCollectionItemRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreScanCollectionItem(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoreScanCollectionItemRecord>?,
    parentPath: InverseForeignKey<out Record, CoreScanCollectionItemRecord>?,
    aliased: Table<CoreScanCollectionItemRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoreScanCollectionItemRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.core_scan_collection_item</code>
         */
        val CORE_SCAN_COLLECTION_ITEM: CoreScanCollectionItem = CoreScanCollectionItem()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoreScanCollectionItemRecord> = CoreScanCollectionItemRecord::class.java

    /**
     * The column <code>public.core_scan_collection_item.id</code>.
     */
    val ID: TableField<CoreScanCollectionItemRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_scan_collection_item.app_id</code>.
     */
    val APP_ID: TableField<CoreScanCollectionItemRecord, UUID?> = createField(DSL.name("app_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_scan_collection_item.collection_id</code>.
     */
    val COLLECTION_ID: TableField<CoreScanCollectionItemRecord, UUID?> = createField(DSL.name("collection_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_scan_collection_item.scan_record_id</code>.
     */
    val SCAN_RECORD_ID: TableField<CoreScanCollectionItemRecord, UUID?> = createField(DSL.name("scan_record_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_scan_collection_item.created_at</code>.
     */
    val CREATED_AT: TableField<CoreScanCollectionItemRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_scan_collection_item.updated_at</code>.
     */
    val UPDATED_AT: TableField<CoreScanCollectionItemRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_scan_collection_item.deleted_at</code>.
     */
    val DELETED_AT: TableField<CoreScanCollectionItemRecord, OffsetDateTime?> = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    private constructor(alias: Name, aliased: Table<CoreScanCollectionItemRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoreScanCollectionItemRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoreScanCollectionItemRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.core_scan_collection_item</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.core_scan_collection_item</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.core_scan_collection_item</code> table reference
     */
    constructor(): this(DSL.name("core_scan_collection_item"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreScanCollectionItemRecord>?, parentPath: InverseForeignKey<out Record, CoreScanCollectionItemRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CORE_SCAN_COLLECTION_ITEM, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CoreScanCollectionItemPath : CoreScanCollectionItem, Path<CoreScanCollectionItemRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreScanCollectionItemRecord>?, parentPath: InverseForeignKey<out Record, CoreScanCollectionItemRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CoreScanCollectionItemRecord>): super(alias, aliased)
        override fun `as`(alias: String): CoreScanCollectionItemPath = CoreScanCollectionItemPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CoreScanCollectionItemPath = CoreScanCollectionItemPath(alias, this)
        override fun `as`(alias: Table<*>): CoreScanCollectionItemPath = CoreScanCollectionItemPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(COLLECTION_ITEM_APP_COLL_IDX, COLLECTION_ITEM_SCAN_RECORD_IDX, COLLECTION_ITEM_SCAN_UQ)
    override fun getPrimaryKey(): UniqueKey<CoreScanCollectionItemRecord> = COLLECTION_ITEM_PKEY
    override fun getReferences(): List<ForeignKey<CoreScanCollectionItemRecord, *>> = listOf(CORE_SCAN_COLLECTION_ITEM__COLLECTION_ITEM_COLLECTION_ID_FKEY, CORE_SCAN_COLLECTION_ITEM__COLLECTION_ITEM_SCAN_RECORD_ID_FKEY)

    /**
     * Get the implicit join path to the
     * <code>public.core_scan_collection</code> table.
     */
    fun coreScanCollection(): CoreScanCollectionPath = coreScanCollection
    val coreScanCollection: CoreScanCollectionPath by lazy { CoreScanCollectionPath(this, CORE_SCAN_COLLECTION_ITEM__COLLECTION_ITEM_COLLECTION_ID_FKEY, null) }

    /**
     * Get the implicit join path to the <code>public.core_scan_record</code>
     * table.
     */
    fun coreScanRecord(): CoreScanRecordPath = coreScanRecord
    val coreScanRecord: CoreScanRecordPath by lazy { CoreScanRecordPath(this, CORE_SCAN_COLLECTION_ITEM__COLLECTION_ITEM_SCAN_RECORD_ID_FKEY, null) }
    override fun `as`(alias: String): CoreScanCollectionItem = CoreScanCollectionItem(DSL.name(alias), this)
    override fun `as`(alias: Name): CoreScanCollectionItem = CoreScanCollectionItem(alias, this)
    override fun `as`(alias: Table<*>): CoreScanCollectionItem = CoreScanCollectionItem(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CoreScanCollectionItem = CoreScanCollectionItem(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CoreScanCollectionItem = CoreScanCollectionItem(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CoreScanCollectionItem = CoreScanCollectionItem(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CoreScanCollectionItem = CoreScanCollectionItem(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CoreScanCollectionItem = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CoreScanCollectionItem = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CoreScanCollectionItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CoreScanCollectionItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CoreScanCollectionItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CoreScanCollectionItem = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CoreScanCollectionItem = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): CoreScanCollectionItem = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): CoreScanCollectionItem = where(DSL.notExists(select))
}
