/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables


import com.ifmix.api.core.infra.jooq.InstantConverter
import com.ifmix.api.core.jooq.Public
import com.ifmix.api.core.jooq.indexes.AGNES_KEY_APP_IDX
import com.ifmix.api.core.jooq.indexes.AGNES_KEY_UNAVAILABLE_IDX
import com.ifmix.api.core.jooq.indexes.AGNES_KEY_UQ
import com.ifmix.api.core.jooq.keys.AGNES_KEY_PKEY
import com.ifmix.api.core.jooq.tables.records.CoreAgnesKeyRecord

import java.time.Instant
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAgnesKey(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoreAgnesKeyRecord>?,
    parentPath: InverseForeignKey<out Record, CoreAgnesKeyRecord>?,
    aliased: Table<CoreAgnesKeyRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoreAgnesKeyRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.core_agnes_key</code>
         */
        val CORE_AGNES_KEY: CoreAgnesKey = CoreAgnesKey()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoreAgnesKeyRecord> = CoreAgnesKeyRecord::class.java

    /**
     * The column <code>public.core_agnes_key.id</code>.
     */
    val ID: TableField<CoreAgnesKeyRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_agnes_key.app_id</code>.
     */
    val APP_ID: TableField<CoreAgnesKeyRecord, UUID?> = createField(DSL.name("app_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_agnes_key.key</code>.
     */
    val KEY: TableField<CoreAgnesKeyRecord, String?> = createField(DSL.name("key"), SQLDataType.VARCHAR(512).nullable(false), this, "")

    /**
     * The column <code>public.core_agnes_key.email</code>.
     */
    val EMAIL: TableField<CoreAgnesKeyRecord, String?> = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.core_agnes_key.rate_limit</code>.
     */
    val RATE_LIMIT: TableField<CoreAgnesKeyRecord, Long?> = createField(DSL.name("rate_limit"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.BIGINT)), this, "")

    /**
     * The column <code>public.core_agnes_key.window_sec</code>.
     */
    val WINDOW_SEC: TableField<CoreAgnesKeyRecord, Long?> = createField(DSL.name("window_sec"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("86400"), SQLDataType.BIGINT)), this, "")

    /**
     * The column <code>public.core_agnes_key.models</code>.
     */
    val MODELS: TableField<CoreAgnesKeyRecord, String?> = createField(DSL.name("models"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.core_agnes_key.unavailable_until</code>.
     */
    val UNAVAILABLE_UNTIL: TableField<CoreAgnesKeyRecord, Instant?> = createField(DSL.name("unavailable_until"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", InstantConverter())

    /**
     * The column <code>public.core_agnes_key.created_at</code>.
     */
    val CREATED_AT: TableField<CoreAgnesKeyRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", InstantConverter())

    /**
     * The column <code>public.core_agnes_key.updated_at</code>.
     */
    val UPDATED_AT: TableField<CoreAgnesKeyRecord, Instant?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", InstantConverter())

    /**
     * The column <code>public.core_agnes_key.deleted_at</code>.
     */
    val DELETED_AT: TableField<CoreAgnesKeyRecord, Instant?> = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", InstantConverter())

    /**
     * The column <code>public.core_agnes_key.type</code>.
     */
    val TYPE: TableField<CoreAgnesKeyRecord, Short?> = createField(DSL.name("type"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("100"), SQLDataType.SMALLINT)), this, "")

    private constructor(alias: Name, aliased: Table<CoreAgnesKeyRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoreAgnesKeyRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoreAgnesKeyRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.core_agnes_key</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.core_agnes_key</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.core_agnes_key</code> table reference
     */
    constructor(): this(DSL.name("core_agnes_key"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(AGNES_KEY_APP_IDX, AGNES_KEY_UNAVAILABLE_IDX, AGNES_KEY_UQ)
    override fun getPrimaryKey(): UniqueKey<CoreAgnesKeyRecord> = AGNES_KEY_PKEY
    override fun `as`(alias: String): CoreAgnesKey = CoreAgnesKey(DSL.name(alias), this)
    override fun `as`(alias: Name): CoreAgnesKey = CoreAgnesKey(alias, this)
    override fun `as`(alias: Table<*>): CoreAgnesKey = CoreAgnesKey(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CoreAgnesKey = CoreAgnesKey(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CoreAgnesKey = CoreAgnesKey(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CoreAgnesKey = CoreAgnesKey(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CoreAgnesKey = CoreAgnesKey(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CoreAgnesKey = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CoreAgnesKey = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CoreAgnesKey = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CoreAgnesKey = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CoreAgnesKey = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CoreAgnesKey = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CoreAgnesKey = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): CoreAgnesKey = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): CoreAgnesKey = where(DSL.notExists(select))
}
