/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables


import com.ifmix.api.core.jooq.Public
import com.ifmix.api.core.jooq.indexes.TODO_ITEM_APP_ID_ID_IDX
import com.ifmix.api.core.jooq.indexes.TODO_ITEM_TODO_ID_IDX
import com.ifmix.api.core.jooq.keys.TODO_ITEM_PKEY
import com.ifmix.api.core.jooq.tables.records.CoreTodoItemRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreTodoItem(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoreTodoItemRecord>?,
    parentPath: InverseForeignKey<out Record, CoreTodoItemRecord>?,
    aliased: Table<CoreTodoItemRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoreTodoItemRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.core_todo_item</code>
         */
        val CORE_TODO_ITEM: CoreTodoItem = CoreTodoItem()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoreTodoItemRecord> = CoreTodoItemRecord::class.java

    /**
     * The column <code>public.core_todo_item.id</code>.
     */
    val ID: TableField<CoreTodoItemRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_todo_item.todo_id</code>.
     */
    val TODO_ID: TableField<CoreTodoItemRecord, UUID?> = createField(DSL.name("todo_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_todo_item.app_id</code>.
     */
    val APP_ID: TableField<CoreTodoItemRecord, UUID?> = createField(DSL.name("app_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_todo_item.content</code>.
     */
    val CONTENT: TableField<CoreTodoItemRecord, String?> = createField(DSL.name("content"), SQLDataType.VARCHAR(1000).nullable(false), this, "")

    /**
     * The column <code>public.core_todo_item.done</code>.
     */
    val DONE: TableField<CoreTodoItemRecord, Boolean?> = createField(DSL.name("done"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.core_todo_item.created_at</code>.
     */
    val CREATED_AT: TableField<CoreTodoItemRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.core_todo_item.updated_at</code>.
     */
    val UPDATED_AT: TableField<CoreTodoItemRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.core_todo_item.deleted_at</code>.
     */
    val DELETED_AT: TableField<CoreTodoItemRecord, OffsetDateTime?> = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    private constructor(alias: Name, aliased: Table<CoreTodoItemRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoreTodoItemRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoreTodoItemRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.core_todo_item</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.core_todo_item</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.core_todo_item</code> table reference
     */
    constructor(): this(DSL.name("core_todo_item"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(TODO_ITEM_APP_ID_ID_IDX, TODO_ITEM_TODO_ID_IDX)
    override fun getPrimaryKey(): UniqueKey<CoreTodoItemRecord> = TODO_ITEM_PKEY
    override fun `as`(alias: String): CoreTodoItem = CoreTodoItem(DSL.name(alias), this)
    override fun `as`(alias: Name): CoreTodoItem = CoreTodoItem(alias, this)
    override fun `as`(alias: Table<*>): CoreTodoItem = CoreTodoItem(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CoreTodoItem = CoreTodoItem(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CoreTodoItem = CoreTodoItem(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CoreTodoItem = CoreTodoItem(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CoreTodoItem = CoreTodoItem(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CoreTodoItem = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CoreTodoItem = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CoreTodoItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CoreTodoItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CoreTodoItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CoreTodoItem = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CoreTodoItem = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): CoreTodoItem = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): CoreTodoItem = where(DSL.notExists(select))
}
