/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables


import com.ifmix.api.core.jooq.Public
import com.ifmix.api.core.jooq.indexes.AUTH_PROVIDER_IDENTITY_IDX
import com.ifmix.api.core.jooq.indexes.AUTH_PROVIDER_UQ
import com.ifmix.api.core.jooq.keys.AUTH_PROVIDER_IDENTITY_PKEY
import com.ifmix.api.core.jooq.keys.CORE_AUTH_PROVIDER_IDENTITY__AUTH_PROVIDER_IDENTITY_AUTH_IDENTITY_ID_FKEY
import com.ifmix.api.core.jooq.keys.CORE_AUTH_PROVIDER_IDENTITY__AUTH_PROVIDER_IDENTITY_AUTH_TENANT_ID_FKEY
import com.ifmix.api.core.jooq.tables.CoreAuthIdentity.CoreAuthIdentityPath
import com.ifmix.api.core.jooq.tables.CoreAuthTenant.CoreAuthTenantPath
import com.ifmix.api.core.jooq.tables.records.CoreAuthProviderIdentityRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAuthProviderIdentity(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoreAuthProviderIdentityRecord>?,
    parentPath: InverseForeignKey<out Record, CoreAuthProviderIdentityRecord>?,
    aliased: Table<CoreAuthProviderIdentityRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoreAuthProviderIdentityRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.core_auth_provider_identity</code>
         */
        val CORE_AUTH_PROVIDER_IDENTITY: CoreAuthProviderIdentity = CoreAuthProviderIdentity()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoreAuthProviderIdentityRecord> = CoreAuthProviderIdentityRecord::class.java

    /**
     * The column <code>public.core_auth_provider_identity.id</code>.
     */
    val ID: TableField<CoreAuthProviderIdentityRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>public.core_auth_provider_identity.auth_tenant_id</code>.
     */
    val AUTH_TENANT_ID: TableField<CoreAuthProviderIdentityRecord, UUID?> = createField(DSL.name("auth_tenant_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>public.core_auth_provider_identity.auth_identity_id</code>.
     */
    val AUTH_IDENTITY_ID: TableField<CoreAuthProviderIdentityRecord, UUID?> = createField(DSL.name("auth_identity_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_auth_provider_identity.provider</code>.
     */
    val PROVIDER: TableField<CoreAuthProviderIdentityRecord, String?> = createField(DSL.name("provider"), SQLDataType.VARCHAR(32).nullable(false), this, "")

    /**
     * The column
     * <code>public.core_auth_provider_identity.provider_account_id</code>.
     */
    val PROVIDER_ACCOUNT_ID: TableField<CoreAuthProviderIdentityRecord, String?> = createField(DSL.name("provider_account_id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.core_auth_provider_identity.email</code>.
     */
    val EMAIL: TableField<CoreAuthProviderIdentityRecord, String?> = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column
     * <code>public.core_auth_provider_identity.email_verified</code>.
     */
    val EMAIL_VERIFIED: TableField<CoreAuthProviderIdentityRecord, Boolean?> = createField(DSL.name("email_verified"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.core_auth_provider_identity.phone</code>.
     */
    val PHONE: TableField<CoreAuthProviderIdentityRecord, String?> = createField(DSL.name("phone"), SQLDataType.VARCHAR(50), this, "")

    /**
     * The column <code>public.core_auth_provider_identity.user_metadata</code>.
     */
    val USER_METADATA: TableField<CoreAuthProviderIdentityRecord, JSONB?> = createField(DSL.name("user_metadata"), SQLDataType.JSONB, this, "")

    /**
     * The column
     * <code>public.core_auth_provider_identity.provider_metadata</code>.
     */
    val PROVIDER_METADATA: TableField<CoreAuthProviderIdentityRecord, JSONB?> = createField(DSL.name("provider_metadata"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.core_auth_provider_identity.login_ip</code>.
     */
    val LOGIN_IP: TableField<CoreAuthProviderIdentityRecord, String?> = createField(DSL.name("login_ip"), SQLDataType.VARCHAR(45), this, "")

    /**
     * The column
     * <code>public.core_auth_provider_identity.login_install_id</code>.
     */
    val LOGIN_INSTALL_ID: TableField<CoreAuthProviderIdentityRecord, UUID?> = createField(DSL.name("login_install_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.core_auth_provider_identity.login_app_id</code>.
     */
    val LOGIN_APP_ID: TableField<CoreAuthProviderIdentityRecord, UUID?> = createField(DSL.name("login_app_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.core_auth_provider_identity.created_at</code>.
     */
    val CREATED_AT: TableField<CoreAuthProviderIdentityRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_auth_provider_identity.updated_at</code>.
     */
    val UPDATED_AT: TableField<CoreAuthProviderIdentityRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<CoreAuthProviderIdentityRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoreAuthProviderIdentityRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoreAuthProviderIdentityRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.core_auth_provider_identity</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.core_auth_provider_identity</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.core_auth_provider_identity</code> table reference
     */
    constructor(): this(DSL.name("core_auth_provider_identity"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreAuthProviderIdentityRecord>?, parentPath: InverseForeignKey<out Record, CoreAuthProviderIdentityRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CORE_AUTH_PROVIDER_IDENTITY, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CoreAuthProviderIdentityPath : CoreAuthProviderIdentity, Path<CoreAuthProviderIdentityRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreAuthProviderIdentityRecord>?, parentPath: InverseForeignKey<out Record, CoreAuthProviderIdentityRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CoreAuthProviderIdentityRecord>): super(alias, aliased)
        override fun `as`(alias: String): CoreAuthProviderIdentityPath = CoreAuthProviderIdentityPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CoreAuthProviderIdentityPath = CoreAuthProviderIdentityPath(alias, this)
        override fun `as`(alias: Table<*>): CoreAuthProviderIdentityPath = CoreAuthProviderIdentityPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(AUTH_PROVIDER_IDENTITY_IDX, AUTH_PROVIDER_UQ)
    override fun getPrimaryKey(): UniqueKey<CoreAuthProviderIdentityRecord> = AUTH_PROVIDER_IDENTITY_PKEY
    override fun getReferences(): List<ForeignKey<CoreAuthProviderIdentityRecord, *>> = listOf(CORE_AUTH_PROVIDER_IDENTITY__AUTH_PROVIDER_IDENTITY_AUTH_IDENTITY_ID_FKEY, CORE_AUTH_PROVIDER_IDENTITY__AUTH_PROVIDER_IDENTITY_AUTH_TENANT_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.core_auth_identity</code>
     * table.
     */
    fun coreAuthIdentity(): CoreAuthIdentityPath = coreAuthIdentity
    val coreAuthIdentity: CoreAuthIdentityPath by lazy { CoreAuthIdentityPath(this, CORE_AUTH_PROVIDER_IDENTITY__AUTH_PROVIDER_IDENTITY_AUTH_IDENTITY_ID_FKEY, null) }

    /**
     * Get the implicit join path to the <code>public.core_auth_tenant</code>
     * table.
     */
    fun coreAuthTenant(): CoreAuthTenantPath = coreAuthTenant
    val coreAuthTenant: CoreAuthTenantPath by lazy { CoreAuthTenantPath(this, CORE_AUTH_PROVIDER_IDENTITY__AUTH_PROVIDER_IDENTITY_AUTH_TENANT_ID_FKEY, null) }
    override fun `as`(alias: String): CoreAuthProviderIdentity = CoreAuthProviderIdentity(DSL.name(alias), this)
    override fun `as`(alias: Name): CoreAuthProviderIdentity = CoreAuthProviderIdentity(alias, this)
    override fun `as`(alias: Table<*>): CoreAuthProviderIdentity = CoreAuthProviderIdentity(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CoreAuthProviderIdentity = CoreAuthProviderIdentity(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CoreAuthProviderIdentity = CoreAuthProviderIdentity(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CoreAuthProviderIdentity = CoreAuthProviderIdentity(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CoreAuthProviderIdentity = CoreAuthProviderIdentity(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CoreAuthProviderIdentity = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CoreAuthProviderIdentity = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CoreAuthProviderIdentity = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CoreAuthProviderIdentity = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CoreAuthProviderIdentity = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CoreAuthProviderIdentity = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CoreAuthProviderIdentity = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): CoreAuthProviderIdentity = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): CoreAuthProviderIdentity = where(DSL.notExists(select))
}
