/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables


import com.ifmix.api.core.jooq.Public
import com.ifmix.api.core.jooq.indexes.APP_CONFIG_BUNDLE_IDX
import com.ifmix.api.core.jooq.indexes.APP_CONFIG_PACKAGE_IDX
import com.ifmix.api.core.jooq.keys.APP_CONFIG_PKEY
import com.ifmix.api.core.jooq.tables.records.CoreAppConfigRevisionRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAppConfigRevision(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoreAppConfigRevisionRecord>?,
    parentPath: InverseForeignKey<out Record, CoreAppConfigRevisionRecord>?,
    aliased: Table<CoreAppConfigRevisionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoreAppConfigRevisionRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.core_app_config_revision</code>
         */
        val CORE_APP_CONFIG_REVISION: CoreAppConfigRevision = CoreAppConfigRevision()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoreAppConfigRevisionRecord> = CoreAppConfigRevisionRecord::class.java

    /**
     * The column <code>public.core_app_config_revision.id</code>.
     */
    val ID: TableField<CoreAppConfigRevisionRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_app_config_revision.app_id</code>.
     */
    val APP_ID: TableField<CoreAppConfigRevisionRecord, UUID?> = createField(DSL.name("app_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_app_config_revision.auth_tenant_id</code>.
     */
    val AUTH_TENANT_ID: TableField<CoreAppConfigRevisionRecord, UUID?> = createField(DSL.name("auth_tenant_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.core_app_config_revision.apple_bundle_id</code>.
     */
    val APPLE_BUNDLE_ID: TableField<CoreAppConfigRevisionRecord, String?> = createField(DSL.name("apple_bundle_id"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column
     * <code>public.core_app_config_revision.android_package_name</code>.
     */
    val ANDROID_PACKAGE_NAME: TableField<CoreAppConfigRevisionRecord, String?> = createField(DSL.name("android_package_name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.core_app_config_revision.revision_number</code>.
     */
    val REVISION_NUMBER: TableField<CoreAppConfigRevisionRecord, Int?> = createField(DSL.name("revision_number"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.core_app_config_revision.created_at</code>.
     */
    val CREATED_AT: TableField<CoreAppConfigRevisionRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_app_config_revision.enabled</code>.
     */
    val ENABLED: TableField<CoreAppConfigRevisionRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.core_app_config_revision.slug</code>.
     */
    val SLUG: TableField<CoreAppConfigRevisionRecord, String?> = createField(DSL.name("slug"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.core_app_config_revision.content</code>.
     */
    val CONTENT: TableField<CoreAppConfigRevisionRecord, JSONB?> = createField(DSL.name("content"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "")

    /**
     * The column <code>public.core_app_config_revision.note</code>.
     */
    val NOTE: TableField<CoreAppConfigRevisionRecord, String?> = createField(DSL.name("note"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "")

    private constructor(alias: Name, aliased: Table<CoreAppConfigRevisionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoreAppConfigRevisionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoreAppConfigRevisionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.core_app_config_revision</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.core_app_config_revision</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.core_app_config_revision</code> table reference
     */
    constructor(): this(DSL.name("core_app_config_revision"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(APP_CONFIG_BUNDLE_IDX, APP_CONFIG_PACKAGE_IDX)
    override fun getPrimaryKey(): UniqueKey<CoreAppConfigRevisionRecord> = APP_CONFIG_PKEY
    override fun `as`(alias: String): CoreAppConfigRevision = CoreAppConfigRevision(DSL.name(alias), this)
    override fun `as`(alias: Name): CoreAppConfigRevision = CoreAppConfigRevision(alias, this)
    override fun `as`(alias: Table<*>): CoreAppConfigRevision = CoreAppConfigRevision(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CoreAppConfigRevision = CoreAppConfigRevision(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CoreAppConfigRevision = CoreAppConfigRevision(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CoreAppConfigRevision = CoreAppConfigRevision(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CoreAppConfigRevision = CoreAppConfigRevision(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CoreAppConfigRevision = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CoreAppConfigRevision = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CoreAppConfigRevision = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CoreAppConfigRevision = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CoreAppConfigRevision = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CoreAppConfigRevision = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CoreAppConfigRevision = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): CoreAppConfigRevision = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): CoreAppConfigRevision = where(DSL.notExists(select))
}
