/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables


import com.ifmix.api.core.jooq.Public
import com.ifmix.api.core.jooq.indexes.APP_USER_UQ
import com.ifmix.api.core.jooq.keys.APP_USER_PKEY
import com.ifmix.api.core.jooq.keys.CORE_APP_REFRESH_TOKEN__APP_REFRESH_TOKEN_APP_USER_ID_FKEY
import com.ifmix.api.core.jooq.keys.CORE_APP_USER__APP_USER_AUTH_IDENTITY_ID_FKEY
import com.ifmix.api.core.jooq.tables.CoreAppRefreshToken.CoreAppRefreshTokenPath
import com.ifmix.api.core.jooq.tables.CoreAuthIdentity.CoreAuthIdentityPath
import com.ifmix.api.core.jooq.tables.records.CoreAppUserRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAppUser(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoreAppUserRecord>?,
    parentPath: InverseForeignKey<out Record, CoreAppUserRecord>?,
    aliased: Table<CoreAppUserRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoreAppUserRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.core_app_user</code>
         */
        val CORE_APP_USER: CoreAppUser = CoreAppUser()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoreAppUserRecord> = CoreAppUserRecord::class.java

    /**
     * The column <code>public.core_app_user.id</code>.
     */
    val ID: TableField<CoreAppUserRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_app_user.app_id</code>.
     */
    val APP_ID: TableField<CoreAppUserRecord, UUID?> = createField(DSL.name("app_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_app_user.auth_identity_id</code>.
     */
    val AUTH_IDENTITY_ID: TableField<CoreAppUserRecord, UUID?> = createField(DSL.name("auth_identity_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_app_user.metadata</code>.
     */
    val METADATA: TableField<CoreAppUserRecord, JSONB?> = createField(DSL.name("metadata"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.core_app_user.created_at</code>.
     */
    val CREATED_AT: TableField<CoreAppUserRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_app_user.updated_at</code>.
     */
    val UPDATED_AT: TableField<CoreAppUserRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<CoreAppUserRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoreAppUserRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoreAppUserRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.core_app_user</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.core_app_user</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.core_app_user</code> table reference
     */
    constructor(): this(DSL.name("core_app_user"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreAppUserRecord>?, parentPath: InverseForeignKey<out Record, CoreAppUserRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CORE_APP_USER, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CoreAppUserPath : CoreAppUser, Path<CoreAppUserRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreAppUserRecord>?, parentPath: InverseForeignKey<out Record, CoreAppUserRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CoreAppUserRecord>): super(alias, aliased)
        override fun `as`(alias: String): CoreAppUserPath = CoreAppUserPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CoreAppUserPath = CoreAppUserPath(alias, this)
        override fun `as`(alias: Table<*>): CoreAppUserPath = CoreAppUserPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(APP_USER_UQ)
    override fun getPrimaryKey(): UniqueKey<CoreAppUserRecord> = APP_USER_PKEY
    override fun getReferences(): List<ForeignKey<CoreAppUserRecord, *>> = listOf(CORE_APP_USER__APP_USER_AUTH_IDENTITY_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.core_auth_identity</code>
     * table.
     */
    fun coreAuthIdentity(): CoreAuthIdentityPath = coreAuthIdentity
    val coreAuthIdentity: CoreAuthIdentityPath by lazy { CoreAuthIdentityPath(this, CORE_APP_USER__APP_USER_AUTH_IDENTITY_ID_FKEY, null) }

    private lateinit var _coreAppRefreshToken: CoreAppRefreshTokenPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.core_app_refresh_token</code> table
     */
    fun coreAppRefreshToken(): CoreAppRefreshTokenPath {
        if (!this::_coreAppRefreshToken.isInitialized)
            _coreAppRefreshToken = CoreAppRefreshTokenPath(this, null, CORE_APP_REFRESH_TOKEN__APP_REFRESH_TOKEN_APP_USER_ID_FKEY.inverseKey)

        return _coreAppRefreshToken;
    }

    val coreAppRefreshToken: CoreAppRefreshTokenPath
        get(): CoreAppRefreshTokenPath = coreAppRefreshToken()
    override fun `as`(alias: String): CoreAppUser = CoreAppUser(DSL.name(alias), this)
    override fun `as`(alias: Name): CoreAppUser = CoreAppUser(alias, this)
    override fun `as`(alias: Table<*>): CoreAppUser = CoreAppUser(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CoreAppUser = CoreAppUser(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CoreAppUser = CoreAppUser(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CoreAppUser = CoreAppUser(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CoreAppUser = CoreAppUser(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CoreAppUser = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CoreAppUser = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CoreAppUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CoreAppUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CoreAppUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CoreAppUser = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CoreAppUser = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): CoreAppUser = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): CoreAppUser = where(DSL.notExists(select))
}
