/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables


import com.ifmix.api.core.jooq.Public
import com.ifmix.api.core.jooq.indexes.REFRESH_APPUSER_IDX
import com.ifmix.api.core.jooq.indexes.REFRESH_DEVICE_IDX
import com.ifmix.api.core.jooq.indexes.REFRESH_TOKEN_UQ
import com.ifmix.api.core.jooq.keys.APP_REFRESH_TOKEN_PKEY
import com.ifmix.api.core.jooq.keys.CORE_APP_REFRESH_TOKEN__APP_REFRESH_TOKEN_APP_USER_ID_FKEY
import com.ifmix.api.core.jooq.keys.CORE_APP_REFRESH_TOKEN__APP_REFRESH_TOKEN_DEVICE_SECRET_ID_FKEY
import com.ifmix.api.core.jooq.tables.CoreAppUser.CoreAppUserPath
import com.ifmix.api.core.jooq.tables.CoreAuthDeviceSecret.CoreAuthDeviceSecretPath
import com.ifmix.api.core.jooq.tables.records.CoreAppRefreshTokenRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreAppRefreshToken(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoreAppRefreshTokenRecord>?,
    parentPath: InverseForeignKey<out Record, CoreAppRefreshTokenRecord>?,
    aliased: Table<CoreAppRefreshTokenRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoreAppRefreshTokenRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.core_app_refresh_token</code>
         */
        val CORE_APP_REFRESH_TOKEN: CoreAppRefreshToken = CoreAppRefreshToken()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoreAppRefreshTokenRecord> = CoreAppRefreshTokenRecord::class.java

    /**
     * The column <code>public.core_app_refresh_token.id</code>.
     */
    val ID: TableField<CoreAppRefreshTokenRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_app_refresh_token.app_id</code>.
     */
    val APP_ID: TableField<CoreAppRefreshTokenRecord, UUID?> = createField(DSL.name("app_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_app_refresh_token.app_user_id</code>.
     */
    val APP_USER_ID: TableField<CoreAppRefreshTokenRecord, UUID?> = createField(DSL.name("app_user_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_app_refresh_token.device_secret_id</code>.
     */
    val DEVICE_SECRET_ID: TableField<CoreAppRefreshTokenRecord, UUID?> = createField(DSL.name("device_secret_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.core_app_refresh_token.token_hash</code>.
     */
    val TOKEN_HASH: TableField<CoreAppRefreshTokenRecord, String?> = createField(DSL.name("token_hash"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.core_app_refresh_token.login_install_id</code>.
     */
    val LOGIN_INSTALL_ID: TableField<CoreAppRefreshTokenRecord, UUID?> = createField(DSL.name("login_install_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.core_app_refresh_token.expires_at</code>.
     */
    val EXPIRES_AT: TableField<CoreAppRefreshTokenRecord, OffsetDateTime?> = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.core_app_refresh_token.revoked_at</code>.
     */
    val REVOKED_AT: TableField<CoreAppRefreshTokenRecord, OffsetDateTime?> = createField(DSL.name("revoked_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.core_app_refresh_token.replaced_by</code>.
     */
    val REPLACED_BY: TableField<CoreAppRefreshTokenRecord, UUID?> = createField(DSL.name("replaced_by"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.core_app_refresh_token.created_at</code>.
     */
    val CREATED_AT: TableField<CoreAppRefreshTokenRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_app_refresh_token.updated_at</code>.
     */
    val UPDATED_AT: TableField<CoreAppRefreshTokenRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<CoreAppRefreshTokenRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoreAppRefreshTokenRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoreAppRefreshTokenRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.core_app_refresh_token</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.core_app_refresh_token</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.core_app_refresh_token</code> table reference
     */
    constructor(): this(DSL.name("core_app_refresh_token"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreAppRefreshTokenRecord>?, parentPath: InverseForeignKey<out Record, CoreAppRefreshTokenRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CORE_APP_REFRESH_TOKEN, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CoreAppRefreshTokenPath : CoreAppRefreshToken, Path<CoreAppRefreshTokenRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoreAppRefreshTokenRecord>?, parentPath: InverseForeignKey<out Record, CoreAppRefreshTokenRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CoreAppRefreshTokenRecord>): super(alias, aliased)
        override fun `as`(alias: String): CoreAppRefreshTokenPath = CoreAppRefreshTokenPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CoreAppRefreshTokenPath = CoreAppRefreshTokenPath(alias, this)
        override fun `as`(alias: Table<*>): CoreAppRefreshTokenPath = CoreAppRefreshTokenPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(REFRESH_APPUSER_IDX, REFRESH_DEVICE_IDX, REFRESH_TOKEN_UQ)
    override fun getPrimaryKey(): UniqueKey<CoreAppRefreshTokenRecord> = APP_REFRESH_TOKEN_PKEY
    override fun getReferences(): List<ForeignKey<CoreAppRefreshTokenRecord, *>> = listOf(CORE_APP_REFRESH_TOKEN__APP_REFRESH_TOKEN_APP_USER_ID_FKEY, CORE_APP_REFRESH_TOKEN__APP_REFRESH_TOKEN_DEVICE_SECRET_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.core_app_user</code>
     * table.
     */
    fun coreAppUser(): CoreAppUserPath = coreAppUser
    val coreAppUser: CoreAppUserPath by lazy { CoreAppUserPath(this, CORE_APP_REFRESH_TOKEN__APP_REFRESH_TOKEN_APP_USER_ID_FKEY, null) }

    /**
     * Get the implicit join path to the
     * <code>public.core_auth_device_secret</code> table.
     */
    fun coreAuthDeviceSecret(): CoreAuthDeviceSecretPath = coreAuthDeviceSecret
    val coreAuthDeviceSecret: CoreAuthDeviceSecretPath by lazy { CoreAuthDeviceSecretPath(this, CORE_APP_REFRESH_TOKEN__APP_REFRESH_TOKEN_DEVICE_SECRET_ID_FKEY, null) }
    override fun `as`(alias: String): CoreAppRefreshToken = CoreAppRefreshToken(DSL.name(alias), this)
    override fun `as`(alias: Name): CoreAppRefreshToken = CoreAppRefreshToken(alias, this)
    override fun `as`(alias: Table<*>): CoreAppRefreshToken = CoreAppRefreshToken(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CoreAppRefreshToken = CoreAppRefreshToken(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CoreAppRefreshToken = CoreAppRefreshToken(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CoreAppRefreshToken = CoreAppRefreshToken(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CoreAppRefreshToken = CoreAppRefreshToken(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CoreAppRefreshToken = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CoreAppRefreshToken = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CoreAppRefreshToken = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CoreAppRefreshToken = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CoreAppRefreshToken = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CoreAppRefreshToken = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CoreAppRefreshToken = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): CoreAppRefreshToken = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): CoreAppRefreshToken = where(DSL.notExists(select))
}
