/*
 * This file is generated by jOOQ.
 */
package com.ifmix.api.core.jooq.tables


import com.ifmix.api.core.jooq.Public
import com.ifmix.api.core.jooq.indexes.USER_INSTALL_BINDING_APP_INSTALL_IDX
import com.ifmix.api.core.jooq.indexes.USER_INSTALL_BINDING_APP_USER_IDX
import com.ifmix.api.core.jooq.indexes.USER_INSTALL_BINDING_UQ
import com.ifmix.api.core.jooq.keys.CORE_USER_INSTALL_BINDING_PKEY
import com.ifmix.api.core.jooq.tables.records.CoreUserInstallBindingRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CoreUserInstallBinding(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoreUserInstallBindingRecord>?,
    parentPath: InverseForeignKey<out Record, CoreUserInstallBindingRecord>?,
    aliased: Table<CoreUserInstallBindingRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoreUserInstallBindingRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.core_user_install_binding</code>
         */
        val CORE_USER_INSTALL_BINDING: CoreUserInstallBinding = CoreUserInstallBinding()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoreUserInstallBindingRecord> = CoreUserInstallBindingRecord::class.java

    /**
     * The column <code>public.core_user_install_binding.id</code>.
     */
    val ID: TableField<CoreUserInstallBindingRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_user_install_binding.app_id</code>.
     */
    val APP_ID: TableField<CoreUserInstallBindingRecord, UUID?> = createField(DSL.name("app_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_user_install_binding.user_id</code>.
     */
    val USER_ID: TableField<CoreUserInstallBindingRecord, UUID?> = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_user_install_binding.install_id</code>.
     */
    val INSTALL_ID: TableField<CoreUserInstallBindingRecord, UUID?> = createField(DSL.name("install_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.core_user_install_binding.first_seen_at</code>.
     */
    val FIRST_SEEN_AT: TableField<CoreUserInstallBindingRecord, OffsetDateTime?> = createField(DSL.name("first_seen_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_user_install_binding.last_seen_at</code>.
     */
    val LAST_SEEN_AT: TableField<CoreUserInstallBindingRecord, OffsetDateTime?> = createField(DSL.name("last_seen_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_user_install_binding.login_count</code>.
     */
    val LOGIN_COUNT: TableField<CoreUserInstallBindingRecord, Int?> = createField(DSL.name("login_count"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.core_user_install_binding.client_ip</code>.
     */
    val CLIENT_IP: TableField<CoreUserInstallBindingRecord, String?> = createField(DSL.name("client_ip"), SQLDataType.VARCHAR(45), this, "")

    /**
     * The column <code>public.core_user_install_binding.client_platform</code>.
     */
    val CLIENT_PLATFORM: TableField<CoreUserInstallBindingRecord, String?> = createField(DSL.name("client_platform"), SQLDataType.VARCHAR(32), this, "")

    /**
     * The column <code>public.core_user_install_binding.created_at</code>.
     */
    val CREATED_AT: TableField<CoreUserInstallBindingRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.core_user_install_binding.updated_at</code>.
     */
    val UPDATED_AT: TableField<CoreUserInstallBindingRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<CoreUserInstallBindingRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoreUserInstallBindingRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoreUserInstallBindingRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.core_user_install_binding</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.core_user_install_binding</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.core_user_install_binding</code> table reference
     */
    constructor(): this(DSL.name("core_user_install_binding"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(USER_INSTALL_BINDING_APP_INSTALL_IDX, USER_INSTALL_BINDING_APP_USER_IDX, USER_INSTALL_BINDING_UQ)
    override fun getPrimaryKey(): UniqueKey<CoreUserInstallBindingRecord> = CORE_USER_INSTALL_BINDING_PKEY
    override fun `as`(alias: String): CoreUserInstallBinding = CoreUserInstallBinding(DSL.name(alias), this)
    override fun `as`(alias: Name): CoreUserInstallBinding = CoreUserInstallBinding(alias, this)
    override fun `as`(alias: Table<*>): CoreUserInstallBinding = CoreUserInstallBinding(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CoreUserInstallBinding = CoreUserInstallBinding(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CoreUserInstallBinding = CoreUserInstallBinding(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CoreUserInstallBinding = CoreUserInstallBinding(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CoreUserInstallBinding = CoreUserInstallBinding(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CoreUserInstallBinding = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CoreUserInstallBinding = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CoreUserInstallBinding = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CoreUserInstallBinding = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CoreUserInstallBinding = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CoreUserInstallBinding = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CoreUserInstallBinding = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): CoreUserInstallBinding = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): CoreUserInstallBinding = where(DSL.notExists(select))
}
